unpackaged/main/default/objects/Funder__c/Funder__c.object-meta.xml
<CustomObject>
    <description>This is where we send deals to all details will be here about them</description>
    <label>Funder</label>
    <nameField>
        <label>Funder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Submissions__c/Submissions__c.object-meta.xml
<CustomObject>
    <label>Submissions</label>
    <nameField>
        <displayFormat>Submission {000000}</displayFormat>
        <label>Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Submissions__c/fields/Funder__c.field-meta.xml
<CustomField>
    <fullName>Funder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Funder</label>
    <referenceTo>Funder__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Submissions__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Submissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Submissions__c/fields/Submit_Funder_Using_Internal_API__c.field-meta.xml
<CustomField>
    <fullName>Submit_Funder_Using_Internal_API__c</fullName>
    <formula>Funder__r.Submit_Using_Internal_API__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Submit Funder Using Internal API</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/SubmitFunderInternalAPIsManager.cls
public with sharing class SubmitFunderInternalAPIsManager {

    public void executeSubmitToFundersCallouts(List<Submissions__c> submissionList){

        System.debug('Submit_Funder_Using_Internal_API__c Step 1.3: execute called');

        for(Submissions__c submission : submissionList) {
            if(submission.Funder__r.Name == 'Idea Financial'){
                System.debug('Submit_Funder_Using_Internal_API__c Step 1.4: Idea Financial found');
                System.enqueueJob(new IdeaFinancialSubmitApplication(submission.Opportunity__c));
            }
        }
    }
}