unpackaged/main/default/objects/Funder__c/Funder__c.object-meta.xml
<CustomObject>
    <description>This is where we send deals to all details will be here about them</description>
    <label>Funder</label>
    <nameField>
        <label>Funder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Opportunity/fields/Funder__c.field-meta.xml
<CustomField>
    <fullName>Funder__c</fullName>
    <label>Funder</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Submissions__c.field-meta.xml
<CustomField>
    <fullName>Submissions__c</fullName>
    <description>Counts all submissions records that are in the Underwriting status, allowing a validation rule to only allow the stage update to Funded (on Opp) when no submission records are in Underwriting status</description>
    <label>Submissions</label>
    <summaryFilterItems>
        <field>Submissions__c.Bank_Status__c</field>
        <operation>equals</operation>
        <value>Underwriting</value>
    </summaryFilterItems>
    <summaryForeignKey>Submissions__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Submissions__c/Submissions__c.object-meta.xml
<CustomObject>
    <label>Submissions</label>
    <nameField>
        <displayFormat>Submission {000000}</displayFormat>
        <label>Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Submissions__c/fields/Bank_Status__c.field-meta.xml
<CustomField>
    <fullName>Bank_Status__c</fullName>
    <label>Bank Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Underwriting</fullName>
                <default>true</default>
                <label>Underwriting</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Submissions__c/fields/Funder__c.field-meta.xml
<CustomField>
    <fullName>Funder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Funder</label>
    <referenceTo>Funder__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Submissions__c/fields/Time_Until_Approved__c.field-meta.xml
<CustomField>
    <fullName>Time_Until_Approved__c</fullName>
    <label>Time Until Approved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/SubmissionTriggerTest.cls
@isTest
public class SubmissionTriggerTest {
    
    public static testmethod void TestBeforeInsert() {
    	
    	integer count = 1;
        List<Account> accountList = TestDataGenerator.createAccountList(count);
        List<Contact> contactList = TestDataGenerator.createContactList(accountList);
        List<Opportunity> oppList = TestDataGenerator.createOpportunityList(accountList);
        List<Funder__c> funderList = TestDataGenerator.createFunderlist(count);
        List<Submissions__c> submissionList = TestDataGenerator.createSubmissionList(oppList, funderList);

		Test.startTest();
		
		Submissions__c submission = [SELECT Id, Time_Until_Approved__c
					FROM Submissions__c WHERE Id =: submissionList[0].Id];
		System.assertEquals(0, submission.Time_Until_Approved__c);
    	
    	Test.stopTest();
    	
    }
    
    public static testmethod void TestBeforeUpdate() {
    	
    	integer count = 1;
        List<Account> accountList = TestDataGenerator.createAccountList(count);
        List<Contact> contactList = TestDataGenerator.createContactList(accountList);
        List<Opportunity> oppList = TestDataGenerator.createOpportunityList(accountList);
        List<Funder__c> funderList = TestDataGenerator.createFunderlist(count);
        List<Submissions__c> submissionList = TestDataGenerator.createSubmissionList(oppList, funderList, 'Underwriting');

		Test.startTest();

		Submissions__c submission = [SELECT Id, Time_Until_Approved__c
					FROM Submissions__c WHERE Id =: submissionList[0].Id];        
        System.assertEquals(null, submission.Time_Until_Approved__c);
        
		submission.Bank_Status__c = 'Approved';
		update submission;
		
		submission = [SELECT Id, Time_Until_Approved__c
					FROM Submissions__c WHERE Id =: submissionList[0].Id];  
		System.assertEquals(0, submission.Time_Until_Approved__c);
		
		Test.stopTest();
    	
    }
    
     public static testmethod void TestAfterInsert() {
    	
    	integer count = 1;
        List<Account> accountList = TestDataGenerator.createAccountList(count);
        List<Contact> contactList = TestDataGenerator.createContactList(accountList);
        List<Opportunity> oppList = TestDataGenerator.createOpportunityList(accountList);
        oppList[0].StageName = 'Underwriting';
        update oppList;
        List<Funder__c> funderList = TestDataGenerator.createFunderlist(count);
		List<Submissions__c> submissionList = TestDataGenerator.createSubmissionList(oppList, funderList, 'Declined');
		
		Test.startTest();
		
		Opportunity opp = [SELECT Id, StageName FROM Opportunity WHERE Id = :oppList[0].Id];
		System.assertEquals('Underwriting - Declined', opp.StageName);
		
		Test.stopTest();
    	
    }
    
    public static testmethod void TestAfterUpdate() {
    	
    	integer count = 1;
        List<Account> accountList = TestDataGenerator.createAccountList(count);
        List<Contact> contactList = TestDataGenerator.createContactList(accountList);
        List<Opportunity> oppList = TestDataGenerator.createOpportunityList(accountList);
        oppList[0].StageName = 'Underwriting';
        update oppList;
        List<Funder__c> funderList = TestDataGenerator.createFunderlist(count);
		List<Submissions__c> submissionList = TestDataGenerator.createSubmissionList(oppList, funderList, 'Underwriting');

		Test.startTest();
		
		System.assert(oppList[0].StageName != 'Underwriting - Declined');
		submissionList[0].Bank_Status__c = 'Declined';
		update submissionList;
		Opportunity opp = [SELECT Id, StageName FROM Opportunity WHERE Id = :oppList[0].Id];
		System.assertEquals('Underwriting - Declined', opp.StageName);

		Test.stopTest();
    	
    }
    
    public static testmethod void TestAfterDelete() {
    	
    	integer count = 2;
        List<Account> accountList = TestDataGenerator.createAccountList(count);
        List<Contact> contactList = TestDataGenerator.createContactList(accountList);
        List<Opportunity> oppList = TestDataGenerator.createOpportunityList(accountList);
        oppList[0].StageName = 'Underwriting';
        update oppList;
        List<Funder__c> funderList = TestDataGenerator.createFunderlist(2);
        List<Submissions__c> submissionList = TestDataGenerator.createSubmissionList(oppList, funderList, 'Underwriting');

		Test.startTest();
		
		System.assert(oppList[0].StageName != 'Underwriting - Declined');
		submissionList[0].Bank_Status__c = 'Declined';
		update submissionList;
		delete submissionList[1];
		Opportunity opp = [SELECT Id, StageName FROM Opportunity WHERE Id = :oppList[0].Id];
		System.assertEquals('Underwriting - Declined', opp.StageName);
	
		Test.stopTest();
    	
    }
    
}