unpackaged/main/default/objects/Funder__c/Funder__c.object-meta.xml
<CustomObject>
    <description>This is where we send deals to all details will be here about them</description>
    <label>Funder</label>
    <nameField>
        <label>Funder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Funder__c/fields/Approval_Time_In_Hours__c.field-meta.xml
<CustomField>
    <fullName>Approval_Time_In_Hours__c</fullName>
    <description>Average time in hours, which takes for the lender to approve the submissions. Updated by a daily batch operation.</description>
    <label>Approval Time In Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Funder__c/fields/PCT_From_Approved_To_Funded__c.field-meta.xml
<CustomField>
    <fullName>PCT_From_Approved_To_Funded__c</fullName>
    <description>The percentage of "approved" submissions that reached to "funded." A daily schedule job updates it.</description>
    <label>% from "Approved"  to "Funded"</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Submissions__c/Submissions__c.object-meta.xml
<CustomObject>
    <label>Submissions</label>
    <nameField>
        <displayFormat>Submission {000000}</displayFormat>
        <label>Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Submissions__c/fields/Bank_Status__c.field-meta.xml
<CustomField>
    <fullName>Bank_Status__c</fullName>
    <label>Bank Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Underwriting</fullName>
                <default>true</default>
                <label>Underwriting</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Submissions__c/fields/Funder__c.field-meta.xml
<CustomField>
    <fullName>Funder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Funder</label>
    <referenceTo>Funder__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Submissions__c/fields/Time_Until_Approved__c.field-meta.xml
<CustomField>
    <fullName>Time_Until_Approved__c</fullName>
    <label>Time Until Approved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/UpdateFunderStatistics.cls
global class UpdateFunderStatistics implements Schedulable
{
    global void execute(SchedulableContext sc)
    {
        Map<string, decimal> funderAprrovalTimeMap = new Map<string, decimal>();
    	for(AggregateResult ar : [SELECT Funder__c,
    								AVG(Time_Until_Approved__c) AverageApprovalTime
									FROM Submissions__c
									WHERE Time_Until_Approved__c <> null
									GROUP BY Funder__c]) {
			funderAprrovalTimeMap.put((string)ar.get('Funder__c'), (decimal)ar.get('AverageApprovalTime'));
		}
		
		Map<string, Integer> approvedSubmissionMap = new Map<string, Integer>(); 
		for(AggregateResult ar : [SELECT Funder__c, COUNT(Id) NumberOfSubmissions FROM Submissions__c
									WHERE Bank_Status__c = 'Approved'
									OR Bank_Status__c = 'Signed'
									OR Bank_Status__c = 'Funded'
									GROUP BY Funder__c]) {
			approvedSubmissionMap.put((string)ar.get('Funder__c'), (integer)ar.get('NumberOfSubmissions'));
		}
		
		map<string, integer> fundedSubmissionMap = new map<string, integer>(); 
		for(AggregateResult ar : [SELECT Funder__c, COUNT(Id) NumberOfSubmissions
								FROM Submissions__c
								WHERE Bank_Status__c = 'Funded'
								GROUP BY Funder__c]) {
			fundedSubmissionMap.put((string)ar.get('Funder__c'), (integer)ar.get('NumberOfSubmissions'));
		}
		
		Map<string, decimal> pctFromApprovedToFundedMap = new Map<string, decimal>();
		for(string funderId : approvedSubmissionMap.keySet()) {
			integer numberOfApprovedSubmissions = approvedSubmissionMap.get(funderId);
			integer numberOfFundedSubmissions =  fundedSubmissionMap.containsKey(funderId) ? fundedSubmissionMap.get(funderId) : 0;
			pctFromApprovedToFundedMap.put(funderId, 100 * (numberOfFundedSubmissions / (decimal) numberOfApprovedSubmissions));
		}
		
		List<Funder__c> funderList = [SELECT Id FROM Funder__c];
        for(Funder__c funder : funderList) {
        	if(funderAprrovalTimeMap.containsKey(funder.Id))
        		funder.Approval_Time_In_Hours__c = funderAprrovalTimeMap.get(funder.Id);
    		if(pctFromApprovedToFundedMap.containsKey(funder.Id))
        		funder.PCT_From_Approved_To_Funded__c = pctFromApprovedToFundedMap.get(funder.Id);
        }
        update funderList;
    }
   
}