unpackaged/main/default/objects/Funder__c/Funder__c.object-meta.xml
<CustomObject>
    <description>This is where we send deals to all details will be here about them</description>
    <label>Funder</label>
    <nameField>
        <label>Funder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Funder__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Only active Funders are retuned on the Find Banks wizard results</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Funder__c/fields/Cashio_ID__c.field-meta.xml
<CustomField>
    <fullName>Cashio_ID__c</fullName>
    <externalId>true</externalId>
    <label>Cashio ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Funder__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Funder__c/fields/Credit_Score__c.field-meta.xml
<CustomField>
    <fullName>Credit_Score__c</fullName>
    <label>Credit Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Funder__c/fields/Funder_Login_Notes__c.field-meta.xml
<CustomField>
    <fullName>Funder_Login_Notes__c</fullName>
    <label>Funder Login Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Funder__c/fields/Funder_Login_URL__c.field-meta.xml
<CustomField>
    <fullName>Funder_Login_URL__c</fullName>
    <label>Funder Login URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Funder__c/fields/Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Logo_URL__c</fullName>
    <label>Logo URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Funder__c/fields/Merchant_App_URL__c.field-meta.xml
<CustomField>
    <fullName>Merchant_App_URL__c</fullName>
    <label>Merchant App URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Funder__c/fields/Ownership_Percentage_Requirment__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Percentage_Requirment__c</fullName>
    <label>Ownership Percentage Requirment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Funder__c/fields/Requires_Manual_Input__c.field-meta.xml
<CustomField>
    <fullName>Requires_Manual_Input__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Manual Input</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Funder__c/fields/Restricted_Industries__c.field-meta.xml
<CustomField>
    <fullName>Restricted_Industries__c</fullName>
    <label>Restricted Industries</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounting Services</fullName>
            </value>
            <value>
                <fullName>Adult Related</fullName>
            </value>
            <value>
                <fullName>Advertising &amp; Marketing</fullName>
            </value>
            <value>
                <fullName>Advice of Sporting Events</fullName>
            </value>
            <value>
                <fullName>Agency-type business</fullName>
            </value>
            <value>
                <fullName>Agriculture / Farming</fullName>
            </value>
            <value>
                <fullName>Air Conditioning and Heating</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>All churches except SIC</fullName>
            </value>
            <value>
                <fullName>Ambulance Service</fullName>
            </value>
            <value>
                <fullName>Amusement Center</fullName>
            </value>
            <value>
                <fullName>Apparel &amp; Electronics Wholesale</fullName>
            </value>
            <value>
                <fullName>Appliance Repair</fullName>
            </value>
            <value>
                <fullName>Attorneys</fullName>
            </value>
            <value>
                <fullName>ATV Sales</fullName>
            </value>
            <value>
                <fullName>Auction House/Flea Markets</fullName>
            </value>
            <value>
                <fullName>Audio Video Rental &amp; Sales</fullName>
            </value>
            <value>
                <fullName>Auto Auctions</fullName>
            </value>
            <value>
                <fullName>Auto Audio &amp; Detail</fullName>
            </value>
            <value>
                <fullName>Auto Dealer New/Used - No Repairs</fullName>
            </value>
            <value>
                <fullName>Auto Dealer Used/New + Auto Repair</fullName>
            </value>
            <value>
                <fullName>Automotive Auctioneers</fullName>
            </value>
            <value>
                <fullName>Auto Parts &amp; Hardware</fullName>
            </value>
            <value>
                <fullName>Aviation</fullName>
            </value>
            <value>
                <fullName>Bail Bonds</fullName>
            </value>
            <value>
                <fullName>Bankrupt or Declining Franchises</fullName>
            </value>
            <value>
                <fullName>Behavioral/Mental Health Center</fullName>
            </value>
            <value>
                <fullName>Boat &amp; RV Storage</fullName>
            </value>
            <value>
                <fullName>Boat Service Dealership</fullName>
            </value>
            <value>
                <fullName>Bowling Center</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Funder__c/fields/Restricted_States__c.field-meta.xml
<CustomField>
    <fullName>Restricted_States__c</fullName>
    <label>Restricted States</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Funder__c/fields/Time_in_business__c.field-meta.xml
<CustomField>
    <fullName>Time_in_business__c</fullName>
    <label>Time in business (Months)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/CashioAPITest.cls
@isTest
private class CashioAPITest {
    
    @isTest static void testCashioAPI() {
        Funder__c funder = new Funder__c(Ownership_Percentage_Requirment__c = 9,
                                            Restricted_Industries__c = 'Fashion;',
                                            Restricted_States__c = 'IL;',
                                            Time_in_business__c = 1,
                                            Credit_Score__c = 89,
                                            Active__c = true,
                                            Contact_Email__c = 'test@email.com',
                                            Cashio_Id__c = '21',
                                            Logo_URL__c = 'https://s3-us-west-2.amazonaws.com/cashio/lenders/logo_images/000/000/014/thumb/Lender-Logos-Blue-Vine.png?1433268648');
        insert funder;


        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();

        req.requestURI = 'https://cs41.salesforce.com/services/apexrest/Cashio/';  
        req.httpMethod = 'POST';


        RestContext.request = req;
        RestContext.response = res;

        String jsonData = '{"utm_source":"test","utm_medium":"test","utm_campaign":"test","test":"test", "submission_id":"12", "action":"create","name":"ryan middlename parker","business_name":"parker plumbing","phone":"234 666 7744","email":"rparker@aol.com","annual_sales":430009,"credit_score":"above 500","state":"nevada","industry":"plumbing","months_in_business":"more than 2","lenders":[{"id":21,"name":"loanme","website":"www.loanme.com"},{"id":25,"name":"finance store","website":"www.financestore.com"},{"id":27,"name":"ondeck capital","website":"www.ondeck.com"}]}';
        RestContext.request.requestBody = Blob.valueOf(jsonData);

        Test.startTest();
        CashioAPI.createLead();
        Test.stopTest();
    }

    @isTest static void testCashioAPI2() {
        Funder__c funder = new Funder__c(Ownership_Percentage_Requirment__c = 9,
                                            Restricted_Industries__c = 'Fashion;',
                                            Restricted_States__c = 'IL;',
                                            Time_in_business__c = 1,
                                            Credit_Score__c = 89,
                                            Active__c = true,
                                            Contact_Email__c = 'test@email.com',
                                            Cashio_Id__c = '21',
                                            Requires_Manual_Input__c = true,
                                            Funder_Login_URL__c = 'http://loginurl.com',
                                            Funder_Login_Notes__c = 'login notes',
                                            Merchant_App_Url__c = 'http://www.merappurl.com/');
        insert funder;


        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();

        req.requestURI = 'https://cs41.salesforce.com/services/apexrest/Cashio/';  
        req.httpMethod = 'POST';


        RestContext.request = req;
        RestContext.response = res;

        String jsonData = '{"utm_source":"test","utm_medium":"test","utm_campaign":"test","test":"test", "submission_id":"12", "action":"create","name":"Ryan","business_name":"parker plumbing","phone":"234 666 7744","email":"rparker@aol.com","annual_sales":430009,"credit_score":"above 500","state":"nevada","industry":"plumbing","months_in_business":"more than 2","lenders":[{"id":21,"name":"loanme","website":"www.loanme.com"},{"id":25,"name":"finance store","website":"www.financestore.com"},{"id":27,"name":"ondeck capital","website":"www.ondeck.com"}]}';
        RestContext.request.requestBody = Blob.valueOf(jsonData);

        Test.startTest();
        CashioAPI.createLead();
        Test.stopTest();
    }
}