unpackaged/main/default/objects/Funder__c/Funder__c.object-meta.xml
<CustomObject>
    <description>This is where we send deals to all details will be here about them</description>
    <label>Funder</label>
    <nameField>
        <label>Funder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Funder__c/fields/Approval_Time_In_Hours__c.field-meta.xml
<CustomField>
    <fullName>Approval_Time_In_Hours__c</fullName>
    <description>Average time in hours, which takes for the lender to approve the submissions. Updated by a daily batch operation.</description>
    <label>Approval Time In Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Funder__c.field-meta.xml
<CustomField>
    <fullName>Funder__c</fullName>
    <label>Funder</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Submissions__c.field-meta.xml
<CustomField>
    <fullName>Submissions__c</fullName>
    <description>Counts all submissions records that are in the Underwriting status, allowing a validation rule to only allow the stage update to Funded (on Opp) when no submission records are in Underwriting status</description>
    <label>Submissions</label>
    <summaryFilterItems>
        <field>Submissions__c.Bank_Status__c</field>
        <operation>equals</operation>
        <value>Underwriting</value>
    </summaryFilterItems>
    <summaryForeignKey>Submissions__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Submissions__c/Submissions__c.object-meta.xml
<CustomObject>
    <label>Submissions</label>
    <nameField>
        <displayFormat>Submission {000000}</displayFormat>
        <label>Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Submissions__c/fields/Funder__c.field-meta.xml
<CustomField>
    <fullName>Funder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Funder</label>
    <referenceTo>Funder__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Submissions__c/fields/Time_Until_Approved__c.field-meta.xml
<CustomField>
    <fullName>Time_Until_Approved__c</fullName>
    <label>Time Until Approved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/UpdateFunderStatisticsTest.cls
@isTest
public class UpdateFunderStatisticsTest {
    
    public static String CRON_EXP = '0 0 0 18 6 ? 2020';
    public static testmethod void testSchedule() {
    	
    	integer count = 1;
        List<Account> accountList = TestDataGenerator.createAccountList(count);
        List<Contact> contactList = TestDataGenerator.createContactList(accountList);
        List<Opportunity> oppList = TestDataGenerator.createOpportunityList(accountList);
        List<Funder__c> funderList = TestDataGenerator.createFunderlist(count);
        List<Submissions__c> submissionList = TestDataGenerator.createSubmissionList(oppList, funderList);
        
       
        Test.startTest();

        String jobId = System.schedule('ScheduledApexTest',
            CRON_EXP, 
            new UpdateFunderStatistics());
        
        Funder__c funder = [SELECT Id, Approval_Time_In_Hours__c
							FROM Funder__c
							WHERE Id =: funderList[0].Id];
									
        System.assertEquals(null,funder.Approval_Time_In_Hours__c);

        Test.stopTest();
        
        funder = [SELECT Id, Approval_Time_In_Hours__c
							FROM Funder__c
							WHERE Id =: funderList[0].Id];
							
		Submissions__c submission = [SELECT Id, Time_Until_Approved__c
									FROM Submissions__c
									WHERE Id =: submissionList[0].Id];
									
        System.assertEquals(submission.Time_Until_Approved__c, funder.Approval_Time_In_Hours__c);
		
    }
    
}