unpackaged/main/default/objects/Funder__c/Funder__c.object-meta.xml
<CustomObject>
    <description>This is where we send deals to all details will be here about them</description>
    <label>Funder</label>
    <nameField>
        <label>Funder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Opportunity/fields/Application_In_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Application_In_Date_Time__c</fullName>
    <label>Application In Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Application_Missing_Info_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Application_Missing_Info_Date_Time__c</fullName>
    <label>Application Missing Info Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Funder__c.field-meta.xml
<CustomField>
    <fullName>Funder__c</fullName>
    <label>Funder</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Other_Missing_Application_Information__c.field-meta.xml
<CustomField>
    <fullName>Other_Missing_Application_Information__c</fullName>
    <label>Other Missing Application Information</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Ready_To_Submit_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Ready_To_Submit_Date_Time__c</fullName>
    <label>Ready To Submit Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Submissions__c.field-meta.xml
<CustomField>
    <fullName>Submissions__c</fullName>
    <description>Counts all submissions records that are in the Underwriting status, allowing a validation rule to only allow the stage update to Funded (on Opp) when no submission records are in Underwriting status</description>
    <label>Submissions</label>
    <summaryFilterItems>
        <field>Submissions__c.Bank_Status__c</field>
        <operation>equals</operation>
        <value>Underwriting</value>
    </summaryFilterItems>
    <summaryForeignKey>Submissions__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Time_From_App_In_To_App_Missing_Info__c.field-meta.xml
<CustomField>
    <fullName>Time_From_App_In_To_App_Missing_Info__c</fullName>
    <description>Time in hours.</description>
    <label>Time From App In To App Missing Info</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Time_From_App_In_To_App_Ready_To_Submit__c.field-meta.xml
<CustomField>
    <fullName>Time_From_App_In_To_App_Ready_To_Submit__c</fullName>
    <description>Time in hours.</description>
    <label>Time From App In To App Ready To Submit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Submissions__c/Submissions__c.object-meta.xml
<CustomObject>
    <label>Submissions</label>
    <nameField>
        <displayFormat>Submission {000000}</displayFormat>
        <label>Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Submissions__c/fields/Funder__c.field-meta.xml
<CustomField>
    <fullName>Funder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Funder</label>
    <referenceTo>Funder__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/OpportunityStageChangeTSManagerTest.cls
@IsTest
public class OpportunityStageChangeTSManagerTest {
    
    static testmethod void test() {
    	
		Utils.now = DateTime.now();
		DateTime prevTime = null;
		
		integer count = 1;
        List<Account> accountList = TestDataGenerator.createAccountList(count);
        List<Contact> contactList = TestDataGenerator.createContactList(accountList);
        List<Opportunity> oppList = TestDataGenerator.createOpportunityList(accountList);
        List<Funder__c> funderList = TestDataGenerator.createFunderlist(count);
        List<Submissions__c> submissionList = TestDataGenerator.createSubmissionList(oppList, funderList);

        Test.startTest();
        
        Opportunity opp = [SELECT Id, Application_In_Date_Time__c FROM Opportunity WHERE Id =: oppList[0].Id];
        System.assertEquals(opp.Application_In_Date_Time__c, Utils.now);
		
		prevTime = Utils.now;
		Utils.now = DateTime.now().addDays(1);
		opp.StageName = 'Application Missing Info';
		opp.Other_Missing_Application_Information__c = 'Test';
		update opp;
        opp = [SELECT Id, Application_Missing_Info_Date_Time__c, Time_From_App_In_To_App_Missing_Info__c
						FROM Opportunity WHERE Id =: opp.Id];
		System.assertEquals(opp.Application_Missing_Info_Date_Time__c, Utils.now);
		System.assertEquals(opp.Time_From_App_In_To_App_Missing_Info__c, Utils.calculateBH(prevTime, Utils.now));
		
		
		Utils.now = DateTime.now().addDays(2);
		opp.StageName = 'Ready to Submit';
		update opp;
        opp = [SELECT Id, Application_In_Date_Time__c, Ready_To_Submit_Date_Time__c,
        				Time_From_App_In_To_App_Ready_To_Submit__c FROM Opportunity WHERE Id =: opp.Id];
		System.assertEquals(opp.Ready_To_Submit_Date_Time__c, Utils.now);
		System.assertEquals(opp.Time_From_App_In_To_App_Ready_To_Submit__c,
								Utils.calculateBH(opp.Application_In_Date_Time__c, Utils.now));
		
		Test.stopTest();
        
    } 
    
}