unpackaged/main/default/objects/Funder__c/Funder__c.object-meta.xml
<CustomObject>
    <description>This is where we send deals to all details will be here about them</description>
    <label>Funder</label>
    <nameField>
        <label>Funder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/IdeaFinancialAPISettings__c/IdeaFinancialAPISettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>IdeaFinancialAPISettings</label>
</CustomObject>

unpackaged/main/default/objects/IdeaFinancialAPISettings__c/fields/Idea_Funder_Id__c.field-meta.xml
<CustomField>
    <fullName>Idea_Funder_Id__c</fullName>
    <label>Idea Funder Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offers</label>
    <nameField>
        <displayFormat>Offer {00000}</displayFormat>
        <label>Offer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Offer__c/fields/Funder__c.field-meta.xml
<CustomField>
    <fullName>Funder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Funder</label>
    <referenceTo>Funder__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Offer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Offer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not presented</fullName>
                <default>true</default>
                <label>Not presented</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/OfferTriggerHandler.cls
public with sharing class OfferTriggerHandler {

    public void handleAfterUpdate(Map<Id, Offer__c> oldOfferMap, List<Offer__c> newOfferList){

        System.debug('OfferTriggerHandler.handleAfterUpdate called');
        IdeaFinancialAPISettings__c settings = IdeaFinancialAPISettings__c.getOrgDefaults();
        for(Offer__c offer : newOfferList){
            Offer__c oldOffer = oldOfferMap.get(offer.Id);
            if(offer.Funder__c == settings.Idea_Funder_Id__c
                    && offer.Status__c == 'Accepted'
                    && oldOffer.Status__c != 'Accepted'){
                System.debug('Idea Financial offer accepted');
                System.enqueueJob(new IdeaFinancialAcceptOffer(offer.Opportunity__c, offer.Id));
            }
        }
    }
}