unpackaged/main/default/objects/Account/fields/Cell_Phone__c.field-meta.xml
<CustomField>
    <fullName>Cell_Phone__c</fullName>
    <label>Cell Phone</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Cell_Phone__c.field-meta.xml
<CustomField>
    <fullName>Cell_Phone__c</fullName>
    <formula>Account.Cell_Phone__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cell Phone</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This is the Account Email, updated via a workflow to populate this field in order to enable a Email Alert to the Account Email</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>Account.Full_Name_1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <formula>Account.Last_Name_1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Scheduled_Notification__c/Scheduled_Notification__c.object-meta.xml
<CustomObject>
    <label>Scheduled Notification</label>
    <nameField>
        <label>Schedule Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Scheduled_Notification__c/fields/Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>Notification_Date__c</fullName>
    <label>Notification Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Scheduled_Notification__c/fields/Notification_Sent__c.field-meta.xml
<CustomField>
    <fullName>Notification_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notification Sent</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Scheduled_Notification__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Scheduled Notifications</relationshipLabel>
    <relationshipName>Scheduled_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/EmailNotificationScheduleJob.cls
global class EmailNotificationScheduleJob implements Schedulable {
    
   global void execute(SchedulableContext SC) {
       
       List<Scheduled_Notification__c> snList =
           [SELECT Id, Notification_Date__c, Opportunity__c, Notification_Sent__c
           FROM Scheduled_Notification__c WHERE Notification_Date__c <= : Date.today() AND Notification_Sent__c = False];
       List<Id> oppIdList = new List<Id>();
       
       for(Scheduled_Notification__c sn : snList) {
           oppIdList.add(sn.Opportunity__c);
       }
       
       Map<Id, Opportunity> idToOppMap=
           new Map<Id, Opportunity>([SELECT Id, Owner.Email, Cell_Phone__c, Email__c,
                                     First_Name__c, Last_Name__c, Account.Name
                                     FROM Opportunity WHERE Id IN : oppIdList]);
       String baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
       String accountName;
       String fullName;
       String cellPhone;
       String email;
       String opportunityUrl;
       
        OrgWideEmailAddress[] owea = null;
        if(!runningInASandbox()) {
			owea = [select Id from OrgWideEmailAddress where Address = 'admin@emcfinancial.com'];
		} else {
			owea = [select Id from OrgWideEmailAddress where Address = 'yariv.ivry@gmail.com'];
		}
		
        EmailTemplate template = [SELECT Id, Body, Subject, HTMLValue
                                  FROM EmailTemplate WHERE Name='Opportunity Email Notification'];
		for(Scheduled_Notification__c sn : snList){
            
            List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();
            Opportunity opp = idToOppMap.get(sn.Opportunity__c);
            
            accountName = opp.Account.Name;
            fullName = (opp.First_Name__c != null ? opp.First_Name__c : '') + ' ' + (opp.Last_Name__c != null ? opp.Last_Name__c : '');
            cellPhone = opp.Cell_Phone__c != null ? opp.Cell_Phone__c : '';
            email = opp.Email__c != null ? opp.Email__c : '';
            opportunityUrl = baseUrl + '/' + opp.Id;

            String emailBody = String.valueOf(template.HTMLValue);
            emailBody = emailBody.replace('<![CDATA[', '');
            emailBody = emailBody.replace('{!ACCOUNT}', accountName);
            emailBody = emailBody.replace('{!FULL_NAME}', fullName);
            emailBody = emailBody.replace('{!CELL_PHONE}', cellPhone);
            emailBody = emailBody.replace('{!EMAIL}', email);
            emailBody = emailBody.replace('{!OPPORTUNITY_URL}', opportunityUrl);
            emailBody = emailBody.replace(']]>', '');

            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

            if (owea.size() > 0){
                mail.setOrgWideEmailAddressId(owea[0].Id);
            }
            
            System.debug(emailBody);
            String emailSubject = String.valueOf(template.Subject);
            emailSubject = emailSubject.replace('{!ACCOUNT}', accountName);
            emailSubject = emailSubject.replace('{!CELL_PHONE}', cellPhone);
            System.debug(emailSubject);
            mail.setHTMLBody(emailBody);
            mail.setSubject(emailSubject);
            
            System.debug(opp.Owner.Email);
            List<String> targets = new List<String>();
            if(!runningInASandbox()) {
                if(opp.Owner.Email != null){
                    targets.add(opp.Owner.Email);
                }
            } else {
                targets.add(Label.DeveloperEmail);	
            }
            
            mail.setToAddresses(targets);
            emailsToSend.add(mail);
            Messaging.SendEmailResult[] results = Messaging.sendEmail(emailsToSend);
            for(Messaging.SendEmailResult result : results) {
              	Messaging.SendEmailError[] errorList = result.getErrors();
                if(errorList != null && errorList.size() > 0) {
                    System.debug(errorList[0].getMessage());
                }  else {
                    sn.Notification_Sent__c = true;
                    update sn;
                }
            }
            
		}

   }
   
   public Boolean runningInASandbox() {
      return [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
    }
	    
}