unpackaged/main/default/objects/Account/fields/Date_Business_Established__c.field-meta.xml
<CustomField>
    <fullName>Date_Business_Established__c</fullName>
    <label>Business Start Date Under Current Owner</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DBA_Name__c.field-meta.xml
<CustomField>
    <fullName>DBA_Name__c</fullName>
    <description>Merchants doing business as name.</description>
    <label>DBA Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry (Internal EMC)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounting Services</fullName>
            </value>
            <value>
                <fullName>Adult Related</fullName>
            </value>
            <value>
                <fullName>Advertising &amp; Marketing</fullName>
            </value>
            <value>
                <fullName>Advice of Sporting Events</fullName>
            </value>
            <value>
                <fullName>Agency-type business</fullName>
            </value>
            <value>
                <fullName>Agriculture / Farming</fullName>
            </value>
            <value>
                <fullName>Air Conditioning and Heating</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Ambulance Service</fullName>
            </value>
            <value>
                <fullName>Amusement Center</fullName>
            </value>
            <value>
                <fullName>Apparel &amp; Electronics Wholesale</fullName>
            </value>
            <value>
                <fullName>Appliance Repair</fullName>
            </value>
            <value>
                <fullName>Appraisal Service</fullName>
            </value>
            <value>
                <fullName>Architectural Services</fullName>
            </value>
            <value>
                <fullName>Assisted Living Facility</fullName>
            </value>
            <value>
                <fullName>Attorneys</fullName>
            </value>
            <value>
                <fullName>ATV Sales</fullName>
            </value>
            <value>
                <fullName>Auction House/Flea Markets</fullName>
            </value>
            <value>
                <fullName>Audio Video Rental &amp; Sales</fullName>
            </value>
            <value>
                <fullName>Auto Auctions</fullName>
            </value>
            <value>
                <fullName>Auto Dealer New/Used + Auto Repair</fullName>
            </value>
            <value>
                <fullName>Auto Dealer New/Used - No Repairs</fullName>
            </value>
            <value>
                <fullName>Automotive Auctioneers</fullName>
            </value>
            <value>
                <fullName>Auto Parts &amp; Hardware</fullName>
            </value>
            <value>
                <fullName>Auto Repair</fullName>
            </value>
            <value>
                <fullName>Aviation</fullName>
            </value>
            <value>
                <fullName>Bail Bonds</fullName>
            </value>
            <value>
                <fullName>Bankrupt or Declining Franchises</fullName>
            </value>
            <value>
                <fullName>Behavioral/Mental Health Center</fullName>
            </value>
            <value>
                <fullName>Biotech</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Industry_As_stated_on_application__c.field-meta.xml
<CustomField>
    <fullName>Industry_As_stated_on_application__c</fullName>
    <label>Industry - (As stated on application)</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Industry_Cashio__c.field-meta.xml
<CustomField>
    <fullName>Industry_Cashio__c</fullName>
    <label>Industry (Cashio)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Industry_Type__c.field-meta.xml
<CustomField>
    <fullName>Industry_Type__c</fullName>
    <label>Industry Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Partner_1_Credit_Score__c.field-meta.xml
<CustomField>
    <fullName>Partner_1_Credit_Score__c</fullName>
    <label>Credit Score(1)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Percent_of_Ownership_1__c.field-meta.xml
<CustomField>
    <fullName>Percent_of_Ownership_1__c</fullName>
    <defaultValue>1</defaultValue>
    <label>% of Ownership(1)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Funder__c/Funder__c.object-meta.xml
<CustomObject>
    <description>This is where we send deals to all details will be here about them</description>
    <label>Funder</label>
    <nameField>
        <label>Funder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ISO__c/ISO__c.object-meta.xml
<CustomObject>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ISO__c/fields/Approvals__c.field-meta.xml
<CustomField>
    <fullName>Approvals__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Approved</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ISO__c/fields/Declined__c.field-meta.xml
<CustomField>
    <fullName>Declined__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Declined</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ISO__c/fields/Funded__c.field-meta.xml
<CustomField>
    <fullName>Funded__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Funded</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ISO__c/fields/Revive__c.field-meta.xml
<CustomField>
    <fullName>Revive__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Revive</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offers</label>
    <nameField>
        <displayFormat>Offer {00000}</displayFormat>
        <label>Offer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Offer__c/fields/Funder__c.field-meta.xml
<CustomField>
    <fullName>Funder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Funder</label>
    <referenceTo>Funder__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Offer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Funded_Amount__c.field-meta.xml
<CustomField>
    <fullName>Funded_Amount__c</fullName>
    <label>Funded Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Funded_On__c.field-meta.xml
<CustomField>
    <fullName>Funded_On__c</fullName>
    <label>Funded On</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Funder__c.field-meta.xml
<CustomField>
    <fullName>Funder__c</fullName>
    <label>Funder</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <formula>TEXT(Account.Industry__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ISO__c.field-meta.xml
<CustomField>
    <fullName>ISO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>ISO__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Reason_for_Decline__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Decline__c</fullName>
    <label>Reason for Decline</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Credit</fullName>
            </value>
            <value>
                <fullName>Low Monthly Volume</fullName>
            </value>
            <value>
                <fullName>Poor Cash Flow</fullName>
            </value>
            <value>
                <fullName>Unresolved Judgement &amp; Leins</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Current advances outstanding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Submissions__c.field-meta.xml
<CustomField>
    <fullName>Submissions__c</fullName>
    <description>Counts all submissions records that are in the Underwriting status, allowing a validation rule to only allow the stage update to Funded (on Opp) when no submission records are in Underwriting status</description>
    <label>Submissions</label>
    <summaryFilterItems>
        <field>Submissions__c.Bank_Status__c</field>
        <operation>equals</operation>
        <value>Underwriting</value>
    </summaryFilterItems>
    <summaryForeignKey>Submissions__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Submissions__c/Submissions__c.object-meta.xml
<CustomObject>
    <label>Submissions</label>
    <nameField>
        <displayFormat>Submission {000000}</displayFormat>
        <label>Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Submissions__c/fields/Bank_Status__c.field-meta.xml
<CustomField>
    <fullName>Bank_Status__c</fullName>
    <label>Bank Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Underwriting</fullName>
                <default>true</default>
                <label>Underwriting</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Submissions__c/fields/Funded__c.field-meta.xml
<CustomField>
    <fullName>Funded__c</fullName>
    <formula>If(ISPICKVAL( Bank_Status__c , "Funded"), 100,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Funded</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Submissions__c/fields/Funder__c.field-meta.xml
<CustomField>
    <fullName>Funder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Funder</label>
    <referenceTo>Funder__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Submissions__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Submissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/OpportunityTriggerTestClass.cls
@isTest(seeAllData=false)
public class OpportunityTriggerTestClass {

    @TestSetup
    static void setup() {
        TestDataGenerator.createBoxOAuthObject();
    }

    public static testmethod void testTrigger(){
        integer count = 5;
        List<ISO__c> liPartnersToInsert = New List<ISO__c>();
        List<User> liUsersToInsert = New List<User>();
        List<Profile> liProfilesToInsert = New List<Profile>([SELECT Id FROM Profile WHERE Name = 'Standard User']);
        List<Opportunity> liOppsToInsert = New List<Opportunity>();
        List<Account> liAccountsToInsert = New List<Account>();
        List<Offer__c> liOffersToInsert = New List<Offer__c>();
        List<Funder__c> liFundersToInsert = New List<Funder__c>();
        List<Contact> liContactsToInsert = New List<Contact>();
        List<Submissions__c> liSubmissionsToInsert = New List<Submissions__c>();
        //create users
        for(integer j=0; j<2; j++){
            liUsersToInsert.add(New User(
                FirstName = 'Test',
                LastName = 'User ' + j,
                Alias = 'test' + j,
                Username = 'test@testxxxxyyyy' + j + '.com',
                Email = 'test@test.com',
                CommunityNickname = 'test' + j,
                localesidkey='en_US',
                emailencodingkey='UTF-8',
                languagelocalekey='en_US',
                TimeZoneSidKey = 'America/New_York',
                ProfileId = liProfilesToInsert[0].Id
            ));
        }
        insert liUsersToInsert;
        //create accounts
        for(integer z=0; z < count; z++){
            liAccountsToInsert.add(New Account(Name = 'Test Account ' + z,
                                               DBA_Name__c = 'DBA ' + z,
                                               Industry__c = 'Attorneys',
                                               Industry_Cashio__c = 'Attorneys',
                                               Industry_As_stated_on_application__c = 'Attorneys',
                                               Industry_Type__c = 'Attorneys',
                                               Date_Business_Established__c = Date.today(),
                                               Partner_1_Credit_Score__c  = 700,
                                               Percent_of_Ownership_1__c = .5));
            
        }
        insert liAccountsToInsert;

        //create contacts
        for(integer q=0; q < count; q++){
            liContactsToInsert.add(New Contact(FirstName='Test ' + q,
                                                LastName='LastName ' + q,
                                                AccountId=liAccountsToInsert[q].Id));
        }
        insert liContactsToInsert;
        
        //create partners
        for(integer i=0; i < count; i++){
            liPartnersToInsert.add(New ISO__c(Name='Test ISO ' + i, 
                                              OwnerID = liUsersToInsert[0].Id));
        }
        for(integer i=0; i < count; i++){
            liPartnersToInsert.add(New ISO__c(Name='Test ISO ' + i + count, 
                                              OwnerID = liUsersToInsert[1].Id));
        }
        insert liPartnersToInsert;
        
        //create opportunities
        for(integer x=0; x < count; x++){
            liOppsToInsert.add(New Opportunity(Name='Test Opp ' + x,
                                                StageName='Application In',
                                                CloseDate=Date.today().addDays(x),
                                                AccountId=liAccountsToInsert[x].Id,
                                                ISO__c = liPartnersToInsert[x].Id,
                                                OwnerId = liUsersToInsert[1].Id));
        }
        insert liOppsToInsert;
        
        //insert funders
        for(integer n=0; n<count; n++){
            liFundersToInsert.add(New Funder__c(Name='Test Funder ' + n));
        }
        insert(liFundersToInsert);
        
        //insert offers
        for( integer y=0; y < count; y++){
            liOffersToInsert.add(New Offer__c(Opportunity__c=liOppsToInsert[y].Id,
                                              Funder__c=liFundersToInsert[y].Id));
        }
        insert liOffersToInsert;
        
        //insert submissions
        for(integer k=0; k<count; k++){
            liSubmissionsToInsert.add(New Submissions__c(
                Opportunity__c = liOppsToInsert[k].Id,
                Bank_Status__c = 'Funded'
            ));
        }
        insert liSubmissionsToInsert;
        System.assertEquals(count * 2, liPartnersToInsert.size());
        System.assertEquals(count, liOppsToInsert.size());
        test.startTest();
        //update opps
        for(Opportunity o : liOppsToInsert){
            o.StageName = 'Approved';
        }
        update liOppsToInsert;
        System.assertEquals(1, [SELECT Id, Approvals__c from ISO__c where Id =: liPartnersToInsert[0].Id].Approvals__c);
        delete liOppsToInsert[0];
        System.assertEquals(0, [SELECT Id, Approvals__c from ISO__c where Id =: liPartnersToInsert[0].Id].Approvals__c);
        undelete liOppsToInsert[0];
        System.assertEquals(1, [SELECT Id, Approvals__c from ISO__c where Id =: liPartnersToInsert[0].Id].Approvals__c);
        //Test re-parenting of ISO__c
        system.debug(liPartnersToInsert);
        liOppsToInsert[0].ISO__c = liOppsToInsert[1].ISO__c;
        update liOppsToInsert;
        system.debug(liPartnersToInsert);
        System.assertEquals(0, [SELECT Id, Approvals__c from ISO__c where Id =: liPartnersToInsert[0].Id].Approvals__c);
        System.assertEquals(2, [SELECT Id, Approvals__c from ISO__c where Id =: liPartnersToInsert[1].Id].Approvals__c);
        liOppsToInsert[0].ISO__c = liPartnersToInsert[Count + 1].Id;
        liOppsToInsert[1].StageName = 'Declined';
        liOppsToInsert[1].Reason_for_Decline__c = 'Fraud';
        liOppsToInsert[2].StageName = 'Closed Lost';
        liOppsToInsert[3].StageName = 'Funded';
        liOppsToInsert[3].Funded_On__c = Date.Today();
        liOppsToInsert[3].Funded_Amount__c = 150.00;
        update liOppsToInsert;
        System.assertEquals(1, [SELECT Declined__c FROM ISO__c WHERE Id =: liOppsToInsert[1].ISO__c Limit 1][0].Declined__c);
        System.assertEquals(1, [SELECT Revive__c FROM ISO__c WHERE Id =: liOppsToInsert[2].ISO__c Limit 1][0].Revive__c);
        System.assertEquals(1, [SELECT Funded__c FROM ISO__c WHERE Id =: liOppsToInsert[3].ISO__c Limit 1][0].Funded__c);
        test.stopTest();
    }
}