unpackaged/main/default/objects/Account/fields/Date_Business_Established__c.field-meta.xml
<CustomField>
    <fullName>Date_Business_Established__c</fullName>
    <label>Business Start Date Under Current Owner</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DBA_Name__c.field-meta.xml
<CustomField>
    <fullName>DBA_Name__c</fullName>
    <description>Merchants doing business as name.</description>
    <label>DBA Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry (Internal EMC)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounting Services</fullName>
            </value>
            <value>
                <fullName>Adult Related</fullName>
            </value>
            <value>
                <fullName>Advertising &amp; Marketing</fullName>
            </value>
            <value>
                <fullName>Advice of Sporting Events</fullName>
            </value>
            <value>
                <fullName>Agency-type business</fullName>
            </value>
            <value>
                <fullName>Agriculture / Farming</fullName>
            </value>
            <value>
                <fullName>Air Conditioning and Heating</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Ambulance Service</fullName>
            </value>
            <value>
                <fullName>Amusement Center</fullName>
            </value>
            <value>
                <fullName>Apparel &amp; Electronics Wholesale</fullName>
            </value>
            <value>
                <fullName>Appliance Repair</fullName>
            </value>
            <value>
                <fullName>Appraisal Service</fullName>
            </value>
            <value>
                <fullName>Architectural Services</fullName>
            </value>
            <value>
                <fullName>Assisted Living Facility</fullName>
            </value>
            <value>
                <fullName>Attorneys</fullName>
            </value>
            <value>
                <fullName>ATV Sales</fullName>
            </value>
            <value>
                <fullName>Auction House/Flea Markets</fullName>
            </value>
            <value>
                <fullName>Audio Video Rental &amp; Sales</fullName>
            </value>
            <value>
                <fullName>Auto Auctions</fullName>
            </value>
            <value>
                <fullName>Auto Dealer New/Used + Auto Repair</fullName>
            </value>
            <value>
                <fullName>Auto Dealer New/Used - No Repairs</fullName>
            </value>
            <value>
                <fullName>Automotive Auctioneers</fullName>
            </value>
            <value>
                <fullName>Auto Parts &amp; Hardware</fullName>
            </value>
            <value>
                <fullName>Auto Repair</fullName>
            </value>
            <value>
                <fullName>Aviation</fullName>
            </value>
            <value>
                <fullName>Bail Bonds</fullName>
            </value>
            <value>
                <fullName>Bankrupt or Declining Franchises</fullName>
            </value>
            <value>
                <fullName>Behavioral/Mental Health Center</fullName>
            </value>
            <value>
                <fullName>Biotech</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <description>Legal spelling of biz name</description>
    <label>Legal Business Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Partner_1_Credit_Score__c.field-meta.xml
<CustomField>
    <fullName>Partner_1_Credit_Score__c</fullName>
    <label>Credit Score(1)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Percent_of_Ownership_1__c.field-meta.xml
<CustomField>
    <fullName>Percent_of_Ownership_1__c</fullName>
    <defaultValue>1</defaultValue>
    <label>% of Ownership(1)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Expected_Apps_Funded__c.field-meta.xml
<CustomField>
    <fullName>Expected_Apps_Funded__c</fullName>
    <defaultValue>0.6</defaultValue>
    <label>Expected - Apps&gt;Funded%</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Expected_Leads_Apps__c.field-meta.xml
<CustomField>
    <fullName>Expected_Leads_Apps__c</fullName>
    <defaultValue>0.2</defaultValue>
    <label>Expected - Leads&gt;Apps%</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Opportunities_Closed_Lost__c.field-meta.xml
<CustomField>
    <fullName>Opportunities_Closed_Lost__c</fullName>
    <label># Opportunities - Closed Lost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Opportunities_Closed_Won__c.field-meta.xml
<CustomField>
    <fullName>Opportunities_Closed_Won__c</fullName>
    <label># Opportunities - Closed Won</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Opportunities_New_Deal__c.field-meta.xml
<CustomField>
    <fullName>Opportunities_New_Deal__c</fullName>
    <label># Opportunities - New Deal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Opportunities_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Opportunities_Renewal__c</fullName>
    <label># Opportunities - Renewal Type</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Opportunities_Underwriting__c.field-meta.xml
<CustomField>
    <fullName>Opportunities_Underwriting__c</fullName>
    <label># Opportunities – Underwriting</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Client_Bank_Statements__c.field-meta.xml
<CustomField>
    <fullName>Client_Bank_Statements__c</fullName>
    <description>This is where you type the exact missing info for this merchant when it comes to bank statements. If the bank statements are complete just type in the box: "Complete"</description>
    <inlineHelpText>This is where you type the exact missing info for this merchant when it comes to bank statements</inlineHelpText>
    <label>Client Bank Statements:</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Funding_Amt__c.field-meta.xml
<CustomField>
    <fullName>Funding_Amt__c</fullName>
    <label>Funding Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <formula>TEXT(Account.Industry__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OpportunityStages__c/OpportunityStages__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The Custom Setting will contain Opportunity Stages Name and Api Name of Campaign fields that needs to update for that Stage.</description>
    <label>OpportunityStages</label>
</CustomObject>

unpackaged/main/default/objects/OpportunityStages__c/fields/CampaignFieldApiName__c.field-meta.xml
<CustomField>
    <fullName>CampaignFieldApiName__c</fullName>
    <description>The field will Contain the api Name of Campaign Fields that needs to update for Opportunity Stage mentioned as Name of Custom setting.</description>
    <label>CampaignFieldApiName</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OpportunityTypes__c/OpportunityTypes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The Custom setting will contain the values for Type picklist of Opportunity and Api Name of Campaign field that maintains count related to that Picklist value of Opportunity.</description>
    <label>OpportunityTypes</label>
</CustomObject>

unpackaged/main/default/objects/OpportunityTypes__c/fields/Campaign_Opp_Type_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Opp_Type_Api_Name__c</fullName>
    <description>Field will contain the Api name of campaign field that maintains count of Opportunity which are in the Type mentioned as Name.</description>
    <label>Campaign Opp Type Api Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/PopulateCampaignFIeldsForOppTest.cls
/* Test Code coverage for PopulateCampaignFleldsForOppHandler
 *
 *
 *
 *
 */
@isTest
public class PopulateCampaignFIeldsForOppTest {
	
	//Constants
	private static final String  STAGE_CLOSED_WON  = 'Closed Won';               								//Opportunity Stage Name.
	private static final String  STAGE_CLOSED_UNDERWRITTING  = 'Underwriting';               			//Opportunity Stage Name.
	private static final String  STAGE_CLOSED_LOST  = 'Closed Lost';               								//Opportunity Stage Name.  
	private static final String  TYPE_NEW  = 'New Deal';  																	//Opportunity Type Name. 
	private static final String  TYPE_RENEWAL  = 'Renewal';  															//Opportunity Type Name. 
	
	
	/* The method will check  the code coverage of onInsertOpportunityUpdateCampaign method of 
	 * PopulateCampaignFIeldsForOppHandler  class.
	 */
    static testMethod void onInsertOpportunityTest(){
    	//Creating dummy record for Account.
    	Account accRecord = PopulateCampaignFIeldsForOppTest.returnAccount();
    	insert accRecord;
    	
    	//Creating dummy records for Campaign.
    	List<Campaign> lstCampaign = PopulateCampaignFIeldsForOppTest.returnCampaignList();
    	insert lstCampaign;
    	
    	//Creating dummy records for Opportunity.
    	List<Opportunity> lstOpportunities = PopulateCampaignFIeldsForOppTest.returnOpportunityList(accRecord.Id, lstCampaign);
    	
    	Database.SaveResult[] sr =  Database.insert(lstOpportunities);
    	system.assert(sr[0].isSuccess());
    }//End onInsertOpportunityTest method.
    
    
    
    
    /* The method will check  the code coverage of onUpdateOppUpdatecamapign method of 
	 * PopulateCampaignFIeldsForOppHandler  class.
	 */
    static testMethod void onUpdateOpportunityTest(){
    	//Creating dummy record for Account.
    	Account accRecord = PopulateCampaignFIeldsForOppTest.returnAccount();
    	insert accRecord;
    	
    	//Creating dummy records for Campaign.
    	List<Campaign> lstCampaign = PopulateCampaignFIeldsForOppTest.returnCampaignList();
    	insert lstCampaign;
    	
    	//Creating dummy records for Opportunity.
    	List<Opportunity> lstOpportunities = PopulateCampaignFIeldsForOppTest.returnOpportunityList(accRecord.Id, lstCampaign);
    	insert lstOpportunities;
    	
    	lstOpportunities[0].StageName = STAGE_CLOSED_LOST;
    	lstOpportunities[1].Type = TYPE_RENEWAL;
    	lstOpportunities[2].Amount = 44000;
    	lstOpportunities[3].Funding_Amt__c = 22400;
    	
    	//update lstOpportunities;
    	Database.SaveResult[] sr1 =  Database.update(lstOpportunities);
    	system.assert(sr1[0].isSuccess());
    	
    	lstOpportunities[0].StageName = STAGE_CLOSED_WON;
    	lstOpportunities[1].CampaignId = lstCampaign[1].Id;
    	lstOpportunities[2].StageName = STAGE_CLOSED_LOST;
    	//update lstOpportunities;
    	Database.SaveResult[] sr2 =  Database.update(lstOpportunities);
    	system.assert(sr2[0].isSuccess());
    	
    	lstOpportunities[2].StageName = STAGE_CLOSED_WON;
    	lstOpportunities[2].amount = 1000;
    	lstOpportunities[2].Funding_Amt__c = 3000;
    	//update lstOpportunities;
    	Database.SaveResult[] sr3 =  Database.update(lstOpportunities);
    	system.assert(sr3[0].isSuccess());
    	
    }//End onInsertOpportunityTest method.
    
    
    
    /* The method will check  the code coverage of onDeleteOppUpdatecamapign method of 
	 * PopulateCampaignFIeldsForOppHandler  class.
	 */
    static testMethod void onDeletOpportunityTest(){
    	//Creating dummy record for Account.
    	Account accRecord = PopulateCampaignFIeldsForOppTest.returnAccount();
    	insert accRecord;
    	
    	//Creating dummy records for Campaign.
    	List<Campaign> lstCampaign = PopulateCampaignFIeldsForOppTest.returnCampaignList();
    	insert lstCampaign;
    	
    	//Creating dummy records for Opportunity.
    	List<Opportunity> lstOpportunities = PopulateCampaignFIeldsForOppTest.returnOpportunityList(accRecord.Id, lstCampaign);
    	insert lstOpportunities;
    	
    	Database.DeleteResult[] sr =  Database.delete(lstOpportunities);
    	system.assert(sr[0].isSuccess());
    	
    }//End onDeletOpportunityTest method.
    
    
    
    /* Method will return List of Dummy Account record. 
     */
      public static Account returnAccount(){
      	return new Account(Name = 'Tem Account1',
      									  DBA_Name__c = 'DBA Test',
      									  Legal_Name__c = 'Legal Test',
                          Industry__c = 'Test Industry',
                          Date_Business_Established__c = Date.today(),
                          Percent_of_Ownership_1__c = 100,
                          Partner_1_Credit_Score__c = 500);
      }//End returnAccount method.
    
    
    
     /* Method will return List of Dummy Opportunity records. 
     */
      public static List<Opportunity> returnOpportunityList(Id pIdccount, List<Campaign> pLstCampaign){
      	List<Opportunity> lstOpportunities = new List<Opportunity>();
      	for(Integer index = 0; index < 4; index++){
      		lstOpportunities.add(new Opportunity(Name = 'Opp' + index,
      																	 	AccountId = pIdccount,
      																	 	CampaignId = pLstCampaign[0].Id,
      																	 	StageName = STAGE_CLOSED_WON,  
      																	 	Type = TYPE_NEW,
      																	 	Amount = 4000 + index,
      																	 	Funding_Amt__c = 8000 + index,
      																	 	CloseDate = system.today(),
      																	 	Client_Bank_Statements__c = 'Test Bank Statement' + index));
      	}//End for.
      	lstOpportunities[3].StageName = STAGE_CLOSED_UNDERWRITTING;
      	lstOpportunities[3].CampaignId = pLstCampaign[4].Id;
      	lstOpportunities.add(new Opportunity(Name = 'Opp',
      																	 	AccountId = pIdccount,
      																	 	CampaignId = pLstCampaign[0].Id,
      																	 	StageName = STAGE_CLOSED_LOST,  
      																	 	Type = TYPE_RENEWAL,
      																	 	Amount = 4000,
      																	 	Funding_Amt__c = 8000,
      																	 	CloseDate = system.today(),
      																	 	Client_Bank_Statements__c = 'Test Bank Statement5' ));
      	return lstOpportunities;
      }//End returnOpportunityList method.
    
    
    
    /* Method will return List of Dummy Campaign records. 
     */
    public static List<Campaign> returnCampaignList(){
    	List<Campaign> lstCampaigns = new List<Campaign>();
    	for(Integer index = 0; index < 4; index++){
    		lstCampaigns.add(new Campaign(Name = 'Test Camp' + index, 
    															  IsActive = true , 
    															  ActualCost = 2000+index, 
    															  Expected_Apps_Funded__c = 10 + index,
    															   Expected_Leads_Apps__c = 20 + index));
    	}//End for.
    	
    	lstCampaigns.add(new Campaign(Name = 'Test Campaign', 
															  IsActive = false , 
															  ActualCost = 2000, 
															  Expected_Apps_Funded__c = 10,
															  Expected_Leads_Apps__c = 20 ));
    	return lstCampaigns;
    }//End returnCampaignList method.
    
    
    
    /* The method will return the dummy records of OpportunityStages.
     */
     public static List<OpportunityStages__c> returnOpportunityStagesList(){
    	List<OpportunityStages__c> tempOpportunityStagesList = new List<OpportunityStages__c>();
    
    		tempOpportunityStagesList.add(new OpportunityStages__c(Name = STAGE_CLOSED_UNDERWRITTING, CampaignFieldApiName__c = 'Opportunities_Underwriting__c' ));
    		tempOpportunityStagesList.add(new OpportunityStages__c(Name = STAGE_CLOSED_WON, CampaignFieldApiName__c = 'Opportunities_Closed_Won__c' ));
    		tempOpportunityStagesList.add(new OpportunityStages__c(Name = STAGE_CLOSED_LOST, CampaignFieldApiName__c = 'Opportunities_Closed_Lost__c' ));
    	return tempOpportunityStagesList;
    }//End returnOpportunityStagesList Method.
    
    
    /* The method will return the dummy records of OpportunityTypes.
     */
    public static List<OpportunityTypes__c> returnOpportunityTypesList(){
    	List<OpportunityTypes__c> tempOpportunityTypesList = new List<OpportunityTypes__c>();
    
    		tempOpportunityTypesList.add(new OpportunityTypes__c(Name = TYPE_NEW, Campaign_Opp_Type_Api_Name__c = 'Opportunities_New_Deal__c' ));
    		tempOpportunityTypesList.add(new OpportunityTypes__c(Name = TYPE_RENEWAL, Campaign_Opp_Type_Api_Name__c = 'Opportunities_Renewal__c' ));
    	return tempOpportunityTypesList;
    }//End returnOpportunityTypesList Method.
    
}//End PopulateCampaignFIeldsForOppTest class.