unpackaged/main/default/objects/Account/fields/Date_Business_Established__c.field-meta.xml
<CustomField>
    <fullName>Date_Business_Established__c</fullName>
    <label>Business Start Date Under Current Owner</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DBA_Name__c.field-meta.xml
<CustomField>
    <fullName>DBA_Name__c</fullName>
    <description>Merchants doing business as name.</description>
    <label>DBA Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Full_Name_1__c.field-meta.xml
<CustomField>
    <fullName>Full_Name_1__c</fullName>
    <description>First Name of Lead.</description>
    <label>First Name(1)</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry (Internal EMC)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounting Services</fullName>
            </value>
            <value>
                <fullName>Adult Related</fullName>
            </value>
            <value>
                <fullName>Advertising &amp; Marketing</fullName>
            </value>
            <value>
                <fullName>Advice of Sporting Events</fullName>
            </value>
            <value>
                <fullName>Agency-type business</fullName>
            </value>
            <value>
                <fullName>Agriculture / Farming</fullName>
            </value>
            <value>
                <fullName>Air Conditioning and Heating</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Ambulance Service</fullName>
            </value>
            <value>
                <fullName>Amusement Center</fullName>
            </value>
            <value>
                <fullName>Apparel &amp; Electronics Wholesale</fullName>
            </value>
            <value>
                <fullName>Appliance Repair</fullName>
            </value>
            <value>
                <fullName>Appraisal Service</fullName>
            </value>
            <value>
                <fullName>Architectural Services</fullName>
            </value>
            <value>
                <fullName>Assisted Living Facility</fullName>
            </value>
            <value>
                <fullName>Attorneys</fullName>
            </value>
            <value>
                <fullName>ATV Sales</fullName>
            </value>
            <value>
                <fullName>Auction House/Flea Markets</fullName>
            </value>
            <value>
                <fullName>Audio Video Rental &amp; Sales</fullName>
            </value>
            <value>
                <fullName>Auto Auctions</fullName>
            </value>
            <value>
                <fullName>Auto Dealer New/Used + Auto Repair</fullName>
            </value>
            <value>
                <fullName>Auto Dealer New/Used - No Repairs</fullName>
            </value>
            <value>
                <fullName>Automotive Auctioneers</fullName>
            </value>
            <value>
                <fullName>Auto Parts &amp; Hardware</fullName>
            </value>
            <value>
                <fullName>Auto Repair</fullName>
            </value>
            <value>
                <fullName>Aviation</fullName>
            </value>
            <value>
                <fullName>Bail Bonds</fullName>
            </value>
            <value>
                <fullName>Bankrupt or Declining Franchises</fullName>
            </value>
            <value>
                <fullName>Behavioral/Mental Health Center</fullName>
            </value>
            <value>
                <fullName>Biotech</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Last_Name_1__c.field-meta.xml
<CustomField>
    <fullName>Last_Name_1__c</fullName>
    <description>This feeds from the Lead</description>
    <label>Last Name(1)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Partner_1_Credit_Score__c.field-meta.xml
<CustomField>
    <fullName>Partner_1_Credit_Score__c</fullName>
    <label>Credit Score(1)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Percent_of_Ownership_1__c.field-meta.xml
<CustomField>
    <fullName>Percent_of_Ownership_1__c</fullName>
    <defaultValue>1</defaultValue>
    <label>% of Ownership(1)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/State_1__c.field-meta.xml
<CustomField>
    <fullName>State_1__c</fullName>
    <label>State(1)</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Funder__c/Funder__c.object-meta.xml
<CustomObject>
    <description>This is where we send deals to all details will be here about them</description>
    <label>Funder</label>
    <nameField>
        <label>Funder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Funder__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Funder__c/fields/Credit_Score__c.field-meta.xml
<CustomField>
    <fullName>Credit_Score__c</fullName>
    <label>Credit Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Funder__c/fields/Ownership_Percentage_Requirment__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Percentage_Requirment__c</fullName>
    <label>Ownership Percentage Requirment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Funder__c/fields/Restricted_Industries__c.field-meta.xml
<CustomField>
    <fullName>Restricted_Industries__c</fullName>
    <label>Restricted Industries</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounting Services</fullName>
            </value>
            <value>
                <fullName>Adult Related</fullName>
            </value>
            <value>
                <fullName>Advertising &amp; Marketing</fullName>
            </value>
            <value>
                <fullName>Advice of Sporting Events</fullName>
            </value>
            <value>
                <fullName>Agency-type business</fullName>
            </value>
            <value>
                <fullName>Agriculture / Farming</fullName>
            </value>
            <value>
                <fullName>Air Conditioning and Heating</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>All churches except SIC</fullName>
            </value>
            <value>
                <fullName>Ambulance Service</fullName>
            </value>
            <value>
                <fullName>Amusement Center</fullName>
            </value>
            <value>
                <fullName>Apparel &amp; Electronics Wholesale</fullName>
            </value>
            <value>
                <fullName>Appliance Repair</fullName>
            </value>
            <value>
                <fullName>Attorneys</fullName>
            </value>
            <value>
                <fullName>ATV Sales</fullName>
            </value>
            <value>
                <fullName>Auction House/Flea Markets</fullName>
            </value>
            <value>
                <fullName>Audio Video Rental &amp; Sales</fullName>
            </value>
            <value>
                <fullName>Auto Auctions</fullName>
            </value>
            <value>
                <fullName>Auto Audio &amp; Detail</fullName>
            </value>
            <value>
                <fullName>Auto Dealer New/Used - No Repairs</fullName>
            </value>
            <value>
                <fullName>Auto Dealer Used/New + Auto Repair</fullName>
            </value>
            <value>
                <fullName>Automotive Auctioneers</fullName>
            </value>
            <value>
                <fullName>Auto Parts &amp; Hardware</fullName>
            </value>
            <value>
                <fullName>Aviation</fullName>
            </value>
            <value>
                <fullName>Bail Bonds</fullName>
            </value>
            <value>
                <fullName>Bankrupt or Declining Franchises</fullName>
            </value>
            <value>
                <fullName>Behavioral/Mental Health Center</fullName>
            </value>
            <value>
                <fullName>Boat &amp; RV Storage</fullName>
            </value>
            <value>
                <fullName>Boat Service Dealership</fullName>
            </value>
            <value>
                <fullName>Bowling Center</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ISO__c/ISO__c.object-meta.xml
<CustomObject>
    <label>Partner</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ISO__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/ISO__c/fields/Copy_Merchant_on_Approvals__c.field-meta.xml
<CustomField>
    <fullName>Copy_Merchant_on_Approvals__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Copy Merchant on Approvals</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offers</label>
    <nameField>
        <displayFormat>Offer {00000}</displayFormat>
        <label>Offer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Offer__c/fields/Funder__c.field-meta.xml
<CustomField>
    <fullName>Funder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Funder</label>
    <referenceTo>Funder__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <formula>Funder_1__r.Contact_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Email</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This is the Account Email, updated via a workflow to populate this field in order to enable a Email Alert to the Account Email</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Final_Stips__c.field-meta.xml
<CustomField>
    <fullName>Final_Stips__c</fullName>
    <description>Final stipulations text box to populate missing items email</description>
    <label>Final Stips</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Funder__c.field-meta.xml
<CustomField>
    <fullName>Funder__c</fullName>
    <label>Funder</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <formula>TEXT(Account.Industry__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ISO__c.field-meta.xml
<CustomField>
    <fullName>ISO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>ISO__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/PresentSelectedOffersControllerTest.cls
@isTest
private class PresentSelectedOffersControllerTest {
    static testmethod void testController(){
        Profile pf = [Select Id from Profile where Name = 'System Administrator'];

        User user = new User();
        user.FirstName = 'Test';
        user.LastName = 'User';
        user.Email = 'testuser@test123456789.com';
        user.CompanyName = 'test.com';
        user.Title = 'Test User';
        user.Username = 'testuser@test123456789.com';
        user.Alias = 'testuser';
        user.CommunityNickname = 'Test User';
        user.TimeZoneSidKey = 'America/Mexico_City';
        user.LocaleSidKey = 'en_US';
        user.EmailEncodingKey = 'ISO-8859-1';
        user.ProfileId = pf.Id;
        user.LanguageLocaleKey = 'en_US';
        user.Phone = '072-321-3423';
        insert user;

        Account acc = new Account(Name = 'Test Account',
                                    Percent_of_Ownership_1__c = 10,
                                    Industry__c = 'Technology',
                                    State_1__c = 'NY',
                                    Date_Business_Established__c = Date.newInstance(1992, 08, 26),
                                    Partner_1_Credit_Score__c = 90,
                                    DBA_Name__c = 'sda',
                                    Email__c = 'test@email.com',
                                    Full_Name_1__c = 'Test Full Name',
                                    Last_Name_1__c = 'Test Last Name');
        insert acc;

        ISO__c iso = new ISO__c(name = 'Test ISO',
                               Copy_Merchant_on_Approvals__c = true,
                               Contact_Email__c = 'test@test.com');
        insert ISO;
        
        Opportunity opp = new Opportunity(Name = 'Test Opp',
                                            AccountId = acc.Id,
                                            StageName = 'Prospecting',
                                            CloseDate = System.today().addDays(30),
                                            OwnerId = user.Id,
                                         	ISO__c = ISO.Id,
                                         	Final_Stips__c = 'test stips');
        insert opp;

        Funder__c funder = new Funder__c(Ownership_Percentage_Requirment__c = 9,
                                            Restricted_Industries__c = 'Fashion;',
                                            Restricted_States__c = 'IL;',
                                            Time_in_business__c = 1,
                                            Credit_Score__c = 89,
                                            Active__c = true);
        insert funder;

        Offer__c offer = new Offer__c();
        offer.Amount_Advanced__c = 100000;
        offer.Payback_Amount__c = 10000;
        //offer.Number_of_Payments__c = 10;
        offer.Type__c = 'Daily';
        offer.Term__c = 10;
        offer.Lender_Fees__c = 200;
        offer.Daily_Payment__c = 100;
        offer.PSF_Charged__c = 200;
        offer.Opportunity__c = opp.Id;
        offer.Funder__c = funder.Id;
        offer.Commission__c = 100;
        offer.Position__c = '1st';
        insert offer;
		
        Offer__c offer2 = new Offer__c();
        offer2.Amount_Advanced__c = 100000;
        offer2.Payback_Amount__c = 10000;
        //offer.Number_of_Payments__c = 10;
        offer2.Type__c = 'Weekly';
        offer2.Term__c = 10;
        offer2.Lender_Fees__c = 200;
        offer2.Daily_Payment__c = 100;
        offer2.PSF_Charged__c = 200;
        offer2.Opportunity__c = opp.Id;
        offer2.Funder__c = funder.Id;
        offer2.Commission__c = 100;
        offer2.Position__c = '2nd';
        insert offer2;
        
        
        PageReference pageRef = Page.PresentSelectedOffers;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('ids',offer.Id + ',' + offer2.Id);

        PresentSelectedOffersController controller = new PresentSelectedOffersController();
        //controller.offers.add(offer);
        //controller.sendOffersEmail();
        controller.execute();

        controller.validations.add(new PresentSelectedOffersController.ValidationObj(offer, 'String msg'));
        controller.execute();
        List<Offer__c> os = controller.getSelectedOffers();
        List<PresentSelectedOffersController.ValidationObj> vo = controller.getValidations();
        String pp = controller.getParentPage();
        
        pageRef = Page.PresentAndEditSelectedOffers;
        Test.setCurrentPage(pageRef);
        opp.ISO__c = null;
        update opp;
        ApexPages.currentPage().getParameters().put('ids',offer.Id + ',' + offer2.Id);
		ApexPages.currentPage().getParameters().put('isEditPage','true');
        controller = new PresentSelectedOffersController();
		controller.execute();
        controller.sendEditedOffersEmail();
        opp.ISO__c = iso.Id;
        update opp;
		controller = new PresentSelectedOffersController();
		controller.execute();
        controller.emailMsg.cc = 'test@test.com, matt@techingcrew.com';
        controller.sendEditedOffersEmail();
        controller.emailMsg.cc = '';
        controller.sendEditedOffersEmail();
        controller.emailMsg.bcc = 'xxx';
        controller.emailMsg.cc = ',;,';
        controller.sendEditedOffersEmail();
        controller.editEmailSuccess = true;
        Test.setCurrentPage(pageRef);
        controller.execute();
    }
}