unpackaged/main/default/objects/Account/fields/DBA_Name__c.field-meta.xml
<CustomField>
    <fullName>DBA_Name__c</fullName>
    <description>Merchants doing business as name.</description>
    <label>DBA Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Box_OAuth_Object__c/Box_OAuth_Object__c.object-meta.xml
<CustomObject>
    <label>Box OAuth Object</label>
    <nameField>
        <label>Box OAuth Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box OAuth Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Box_OAuth_Object__c/fields/Auth_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Auth_Endpoint__c</fullName>
    <label>Auth Endpoint</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Box_OAuth_Object__c/fields/Auth_Token__c.field-meta.xml
<CustomField>
    <fullName>Auth_Token__c</fullName>
    <label>Auth Token</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Box_OAuth_Object__c/fields/Auth_Token_Expires__c.field-meta.xml
<CustomField>
    <fullName>Auth_Token_Expires__c</fullName>
    <label>Auth Token Expires</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Box_OAuth_Object__c/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <label>Client Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Box_OAuth_Object__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <label>Client Secret</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Box_OAuth_Object__c/fields/Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token__c</fullName>
    <label>Refresh Token</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Box_OAuth_Object__c/fields/Refresh_Token_Expires__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token_Expires__c</fullName>
    <label>Refresh Token Expires</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/BoxFolderCreationTriggerOpp_Test.cls
@isTest
public class BoxFolderCreationTriggerOpp_Test {
    
    static testMethod void insertNewOpportunity() {

		Box_OAuth_Object__c boxAuthObj = new Box_OAuth_Object__c();
		boxAuthObj.Auth_Endpoint__c = '';
		boxAuthObj.Auth_Token__c = '1234567890';
		boxAuthObj.Refresh_Token__c = '1234567890';
		boxAuthObj.Auth_Token_Expires__c = Datetime.now().addSeconds(3600);
		boxAuthObj.Refresh_Token_Expires__c = Datetime.now().addDays(60);
		boxAuthObj.Client_Id__c = '12345';
		boxAuthObj.Client_Secret__c  = '12345';
		insert boxAuthObj;

       	Account a = new Account();
		a.Name='Test Account';
        a.DBA_Name__c='DBA Name';
 		insert a;

		Opportunity opp=new Opportunity();
		opp.Name='Test Oppty';
		Opp.StageName='Prospecting';
		opp.CloseDate=system.today();
		opp.Accountid=a.id;
		insert opp;

    }

}