unpackaged/main/default/objects/Account/fields/DBA_Name__c.field-meta.xml
<CustomField>
    <fullName>DBA_Name__c</fullName>
    <description>Merchants doing business as name.</description>
    <label>DBA Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <description>Legal spelling of biz name</description>
    <label>Legal Business Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
    <relationshipName>Primary_Contact_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TestCopyPrimaryContact.cls
@isTest

private class TestCopyPrimaryContact {
  static testMethod void test() {
    Account a = new account(Name='Fake Account', DBA_Name__c='Fluffy Flap', Legal_Name__c='Fluffy Flap');
    insert a;
    Contact c = new Contact(AccountId=a.id,LastName='Daikoku');
    insert c;
    Opportunity o = new Opportunity(AccountId=a.id,Name='Test Opp',CloseDate=System.today(),StageName='Application In');
    insert o;
    OpportunityContactRole ocr = new OpportunityContactRole(opportunityid=o.id,contactid=c.id,IsPrimary=true,Role='Business Owner');
    insert ocr;
    Test.startTest();
    update o;
    Test.stopTest();
    o = [select id,Primary_Contact__c from opportunity where id = :o.id];
    
  }
}