unpackaged/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This is the Account Email, updated via a workflow to populate this field in order to enable a Email Alert to the Account Email</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Scheduled_Notification__c/Scheduled_Notification__c.object-meta.xml
<CustomObject>
    <label>Scheduled Notification</label>
    <nameField>
        <label>Schedule Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Scheduled_Notification__c/fields/Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>Notification_Date__c</fullName>
    <label>Notification Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Scheduled_Notification__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Scheduled Notifications</relationshipLabel>
    <relationshipName>Scheduled_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/EmailNotificationScheduleJobTest.cls
@istest
public with sharing class EmailNotificationScheduleJobTest {
    
	public static String CRON_EXP = '0 0 0 18 6 ? 2020';
    public static testMethod void testSchedule() {
       
        integer count = 1;
        List<Account> accountList = TestDataGenerator.createAccountList(count);
        List<Contact> contactList = TestDataGenerator.createContactList(accountList);
        List<Opportunity> oppList = TestDataGenerator.createOpportunityList(accountList);
    	Opportunity opp = oppList[0];
    	opp.Email__c = 'test@test.co.il';
    	update opp;

    	Scheduled_Notification__c sn = new Scheduled_Notification__c();
    	sn.Opportunity__c = opp.Id;
        sn.Notification_Date__c = Date.today();
        insert sn;
    	
        Test.startTest();

        String jobId = System.schedule('ScheduledApexTest',
            CRON_EXP, 
            new EmailNotificationScheduleJob());
        
        Test.stopTest();       
		
    }
    
}