unpackaged/main/default/objects/Lead/fields/Form_Step_1__c.field-meta.xml
<CustomField>
    <fullName>Form_Step_1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Form Step 1</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Form_Step_3__c.field-meta.xml
<CustomField>
    <fullName>Form_Step_3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Form Step 3</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/IsEmcForm__c.field-meta.xml
<CustomField>
    <fullName>IsEmcForm__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsEmcForm</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Reminder_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reminder Email Sent</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/SendAbandonedFormEmailBatch.cls
public class SendAbandonedFormEmailBatch implements Database.Batchable<sObject> {
    public List<Lead> start(Database.BatchableContext bc) {

        Datetime startDateTime = Datetime.now().addMinutes(-5);
        Datetime endDateTime = Datetime.now().addMinutes(-11);
//        Datetime startDateTime = Datetime.now().addMinutes(0);
//        Datetime endDateTime = Datetime.now().addMinutes(-30);

        if(Test.isRunningTest()) {
            startDateTime = Datetime.now();
        }

        return [SELECT Id, Email, IsEmcForm__c, Owner.Email FROM Lead WHERE Form_Step_1__c = TRUE
                       AND Form_Step_3__c = FALSE AND Reminder_Email_Sent__c = FALSE
                       AND CreatedDate <= :startDateTime
                       AND CreatedDate >= :endDateTime];

    }
    public void execute(Database.BatchableContext bc, List<Lead> leadList) {
        SendAbandonedFormEmailManager sendAbandonedFormEmailManager = new SendAbandonedFormEmailManager();
        sendAbandonedFormEmailManager.sendEmails(leadList);
    }
    public void finish(Database.BatchableContext bc) {

    }
}