unpackaged/main/default/objects/Scheduled_Notification__c/Scheduled_Notification__c.object-meta.xml
<CustomObject>
    <label>Scheduled Notification</label>
    <nameField>
        <label>Schedule Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Scheduled_Notification__c/fields/Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>Notification_Date__c</fullName>
    <label>Notification Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Scheduled_Notification__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Scheduled Notifications</relationshipLabel>
    <relationshipName>Scheduled_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ScheduleNotificationExtension.cls
public class ScheduleNotificationExtension {
    
    public Opportunity opp {get; set;}  
 	public Scheduled_Notification__c sn {get; set;}
    
    public Boolean succeeded {get; set;} 
   
    public ScheduleNotificationExtension (ApexPages.StandardController stdController) {
        this.opp = (Opportunity)stdController.getRecord();
        this.opp = [SELECT Id, Name, Owner.Name, Owner.Email
                    FROM Opportunity
                    WHERE Id = :this.opp.Id];
        sn = new Scheduled_Notification__c();
    }

    public PageReference notifyTwoWeeks() {
        Date dateToNotify = Date.today().addDays(14);
    	return notify(dateToNotify);
    }
    
    public PageReference notifyOneMonth() {
        Date dateToNotify = Date.today().addMonths(1);
    	return notify(dateToNotify);
    }
    
    public PageReference notify(Date dateToNotify) {
        sn.Opportunity__c = opp.Id;
        sn.Notification_Date__c = dateToNotify;
        insert sn;
        succeeded = true;
    	return null;
    }
    
}