unpackaged/main/default/objects/EmailCollection__c/EmailCollection__c.object-meta.xml
<CustomObject>
    <label>EmailCollection</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EmailCollections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EmailCollection__c/fields/Email_Collection_Type__c.field-meta.xml
<CustomField>
    <fullName>Email_Collection_Type__c</fullName>
    <label>Email Collection Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Email</fullName>
                <default>true</default>
                <label>New Email</label>
            </value>
            <value>
                <fullName>Email Replacement</fullName>
            </value>
            <value>
                <fullName>Fixing Old Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EmailCollection__c/fields/GiveCommission__c.field-meta.xml
<CustomField>
    <fullName>GiveCommission__c</fullName>
    <defaultValue>true</defaultValue>
    <label>GiveCommission</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/EmailCollection__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>EmailCollections</relationshipLabel>
    <relationshipName>EmailCollections</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EmailCollection__c/fields/NewEmail__c.field-meta.xml
<CustomField>
    <fullName>NewEmail__c</fullName>
    <label>NewEmail</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/EmailCollection__c/fields/OldEmail__c.field-meta.xml
<CustomField>
    <fullName>OldEmail__c</fullName>
    <label>OldEmail</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <formula>IF( !IsConverted &amp;&amp; !CONTAINS(Text(Status),'Closed')
,IF(IF(Days_Since_Last_Activity__c &lt;&gt; 0, Days_Since_Last_Activity__c,  Days_From_Creation__c) &gt;= 9.5
,IF(IF(Days_Since_Last_Activity__c &lt;&gt; 0, Days_Since_Last_Activity__c,  Days_From_Creation__c)  &lt; 19.5
,IMAGE("/servlet/servlet.FileDownload?file=0151M00000QWjnP", 'Orange Flag', 40, 40)
,IMAGE("/servlet/servlet.FileDownload?file=0151M00000QWjnK", 'Red Flag', 40, 40))
,'')
,'')</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Since Last Activity Warning</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/EmailCollectionController.cls
public with sharing class EmailCollectionController {
	
	private Lead lead;
	public EmailCollection__c emailCollection {get;set;}
	
	public EmailCollectionController(){}
	
	public EmailCollectionController(ApexPages.StandardController stdController) {
	    this.lead = (Lead)stdController.getRecord();
	    emailCollection = new EmailCollection__c();
        emailCollection.OwnerId = UserInfo.getUserId();
	}
	
    public PageReference CreateEmailCollection() {
        if(this.lead.Email == emailCollection.NewEmail__c) {
            ApexPages.Message msg =
                new ApexPages.Message(ApexPages.Severity.Error, Label.Emails_Are_Equals);
            ApexPages.addMessage(msg);
            return null;
        }
         if(emailCollection.NewEmail__c == null || emailCollection.NewEmail__c == '') {
            ApexPages.Message msg =
                new ApexPages.Message(ApexPages.Severity.Error, Label.New_Email_Field_Is_Required);
            ApexPages.addMessage(msg);
            return null;
        }
        try {
            emailCollection.Lead__c = this.lead.Id;
            //emailCollection.Email_Collection_Type__c;
            emailCollection.OldEmail__c = this.lead.Email;
            insert emailCollection;
            lead.Email = emailCollection.NewEmail__c;
            update this.lead;
            return new PageReference('javascript:window.close()');
        } catch(Exception ex) {
            return null;
        }
    }
    
    public PageReference uncheckGiveCommission() {
    	string emailCollectionId = apexpages.currentpage().getparameters().get('eci');
    	if(emailCollectionId == null || emailCollectionId == '') {
    		 ApexPages.Message msg =
                new ApexPages.Message(ApexPages.Severity.Error, 'An error occurred when trying to update the Email Collection Record.');
            ApexPages.addMessage(msg);
    		return null;
    	}
    	EmailCollection__c emailCollection = [SELECT Id FROM EmailCollection__c WHERE Id = :emailCollectionId];
    	emailCollection.GiveCommission__c = false;
    	update emailCollection;
        return new PageReference('javascript:window.close()');
    }
    
}