unpackaged/main/default/objects/EmailCollection__c/EmailCollection__c.object-meta.xml
<CustomObject>
    <label>EmailCollection</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EmailCollections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EmailCollection__c/fields/Email_Collection_Type__c.field-meta.xml
<CustomField>
    <fullName>Email_Collection_Type__c</fullName>
    <label>Email Collection Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Email</fullName>
                <default>true</default>
                <label>New Email</label>
            </value>
            <value>
                <fullName>Email Replacement</fullName>
            </value>
            <value>
                <fullName>Fixing Old Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EmailCollection__c/fields/GiveCommission__c.field-meta.xml
<CustomField>
    <fullName>GiveCommission__c</fullName>
    <defaultValue>true</defaultValue>
    <label>GiveCommission</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/EmailCollection__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>EmailCollections</relationshipLabel>
    <relationshipName>EmailCollections</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EmailCollection__c/fields/NewEmail__c.field-meta.xml
<CustomField>
    <fullName>NewEmail__c</fullName>
    <label>NewEmail</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/EmailCollection__c/fields/OldEmail__c.field-meta.xml
<CustomField>
    <fullName>OldEmail__c</fullName>
    <label>OldEmail</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <formula>IF( !IsConverted &amp;&amp; !CONTAINS(Text(Status),'Closed')
,IF(IF(Days_Since_Last_Activity__c &lt;&gt; 0, Days_Since_Last_Activity__c,  Days_From_Creation__c) &gt;= 9.5
,IF(IF(Days_Since_Last_Activity__c &lt;&gt; 0, Days_Since_Last_Activity__c,  Days_From_Creation__c)  &lt; 19.5
,IMAGE("/servlet/servlet.FileDownload?file=0151M00000QWjnP", 'Orange Flag', 40, 40)
,IMAGE("/servlet/servlet.FileDownload?file=0151M00000QWjnK", 'Red Flag', 40, 40))
,'')
,'')</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Since Last Activity Warning</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/EmailCollectionControllerTest.cls
@istest
public with sharing class EmailCollectionControllerTest {
	
	Static testmethod void Test(){    
		
		Lead lead = ActivityCountHandlerTest.createLeadRecord();
		lead.Email = 'test@test.com';
    	insert lead;
    	
        PageReference pageRef = Page.Email_Collection;
        pageRef.getparameters().put('recordId', lead.Id);  
        Test.setCurrentPage(pageRef);
        
        Apexpages.StandardController standardController = new Apexpages.StandardController(lead);
        EmailCollectionController emailCollectionController = new  EmailCollectionController(standardController);
        emailCollectionController.emailCollection.NewEmail__c = 'test100@test.com';      
        emailCollectionController.CreateEmailCollection();      
    }
    
	Static testmethod void TestBlankEmail(){    
		
		Lead lead = ActivityCountHandlerTest.createLeadRecord();
    	insert lead;
    	
        PageReference pageRef = Page.Email_Collection;
        pageRef.getparameters().put('recordId', lead.Id);  
        Test.setCurrentPage(pageRef);
        
        Apexpages.StandardController standardController = new Apexpages.StandardController(lead);
        EmailCollectionController emailCollectionController = new  EmailCollectionController(standardController);         
        emailCollectionController.CreateEmailCollection();      
    }
    
    Static testmethod void TestSameEmail(){    
		
		Lead lead = ActivityCountHandlerTest.createLeadRecord();
		lead.Email = 'test@test.com';
    	insert lead;
    	
        PageReference pageRef = Page.Email_Collection;
        pageRef.getparameters().put('recordId', lead.Id);  
        Test.setCurrentPage(pageRef);
        
        Apexpages.StandardController standardController = new Apexpages.StandardController(lead);
        EmailCollectionController emailCollectionController = new  EmailCollectionController(standardController);
        emailCollectionController.emailCollection.NewEmail__c = 'test@test.com';      
        emailCollectionController.CreateEmailCollection();      
    }
    
    Static testmethod void TestUncheckGiveCommission(){    
		
		Lead lead = ActivityCountHandlerTest.createLeadRecord();
		lead.Email = 'test@test.com';
    	insert lead;
    	
    	EmailCollection__c emailCollection = new EmailCollection__c();
		emailCollection.OwnerId = UserInfo.getUserId();
        emailCollection.Lead__c =lead.Id;
        emailCollection.Email_Collection_Type__c = 'New Email';
        emailCollection.OldEmail__c = 'test1@test.com';
        emailCollection.NewEmail__c = 'test2@test.com';
        insert emailCollection;
    	
    	
        PageReference pageRef = Page.Uncheck_Give_Commission;
        pageRef.getparameters().put('eci', emailCollection.Id);  
        Test.setCurrentPage(pageRef);
        
        EmailCollectionController emailCollectionController = new  EmailCollectionController();     
        emailCollectionController.uncheckGiveCommission();
        
        emailCollection = [SELECT Id, GiveCommission__c FROM EmailCollection__c WHERE Id = :emailCollection.Id];
        System.assertEquals(false, emailCollection.GiveCommission__c);
        
    }
    
    Static testmethod void TestUncheckGiveCommissionWrongParameter(){    
		
		Lead lead = ActivityCountHandlerTest.createLeadRecord();
		lead.Email = 'test@test.com';
    	insert lead;
    	
    	EmailCollection__c emailCollection = new EmailCollection__c();
		emailCollection.OwnerId = UserInfo.getUserId();
        emailCollection.Lead__c =lead.Id;
        emailCollection.Email_Collection_Type__c = 'New Email';
        emailCollection.OldEmail__c = 'test1@test.com';
        emailCollection.NewEmail__c = 'test2@test.com';
        insert emailCollection;
    	
    	
        PageReference pageRef = Page.Uncheck_Give_Commission;
        pageRef.getparameters().put('eci', emailCollection.Id);  
        Test.setCurrentPage(pageRef);
        
        EmailCollectionController emailCollectionController = new  EmailCollectionController();     
        emailCollectionController.uncheckGiveCommission();
        
        emailCollection = [SELECT Id, GiveCommission__c FROM EmailCollection__c WHERE Id = :emailCollection.Id];
        System.assertEquals(false, emailCollection.GiveCommission__c);
        
    }
    
}