unpackaged/main/default/objects/DocuSign_Settings__c/DocuSign_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>DocuSign Settings</label>
</CustomObject>

unpackaged/main/default/objects/DocuSign_Settings__c/fields/DocuSign_Powerform_Id__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_Powerform_Id__c</fullName>
    <label>DocuSign Powerform Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/DocuSign_Settings__c/fields/EMC_Application_Form_Path__c.field-meta.xml
<CustomField>
    <fullName>EMC_Application_Form_Path__c</fullName>
    <label>EMC Application Form Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/DocuSign_Settings__c/fields/EMC_Host__c.field-meta.xml
<CustomField>
    <fullName>EMC_Host__c</fullName>
    <label>EMC Host</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/DocuSign_Settings__c/fields/Lendfully_Application_Form_Path__c.field-meta.xml
<CustomField>
    <fullName>Lendfully_Application_Form_Path__c</fullName>
    <label>Lendfully Application Form Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/DocuSign_Settings__c/fields/Lendfully_Host__c.field-meta.xml
<CustomField>
    <fullName>Lendfully_Host__c</fullName>
    <label>Lendfully Host</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ApplicationFormRedirectController.cls
public without sharing class ApplicationFormRedirectController {

    private DocuSign_Settings__c docusignSettings {get; set;}
    private String redirectUrl {get; set;}

    public ApplicationFormRedirectController() {

        docusignSettings = DocuSign_Settings__c.getOrgDefaults();
        String emcHost = docusignSettings.EMC_Host__c;
        String lendfullyHost = docusignSettings.Lendfully_Host__c;
        String emcApplicationFormPath = docusignSettings.EMC_Application_Form_Path__c;
        String lendfullyApplicationFormPath = docusignSettings.Lendfully_Application_Form_Path__c;
        String emcPowerformId = docusignSettings.DocuSign_Powerform_Id__c;


        String currentPowerFormId = ApexPages.currentPage().getParameters().get('pf');
        if(currentPowerFormId != null && currentPowerFormId == emcPowerformId) {
            redirectUrl = emcHost + emcApplicationFormPath;
        } else {
            redirectUrl = lendfullyHost + lendfullyApplicationFormPath;
        }

        String url = ApexPages.currentPage().getUrl();
        if(String.isNotBlank(url) && url.contains('?')) {
            redirectUrl += '?' + url.substringAfter('?');
        }
        if(currentPowerFormId != null && currentPowerFormId == emcPowerformId) {
            redirectUrl += redirectUrl.contains('?') ? '&' :'?';
            redirectUrl += 'emcsite=1';
        }

    }

    public PageReference redirect() {
        PageReference redirect = new PageReference(redirectUrl);
        redirect.setRedirect(true);
        return redirect;
    }

}