unpackaged/main/default/objects/DocuSign_Settings__c/DocuSign_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>DocuSign Settings</label>
</CustomObject>

unpackaged/main/default/objects/DocuSign_Settings__c/fields/DocuSign_Powerform_Id__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_Powerform_Id__c</fullName>
    <label>DocuSign Powerform Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ApplicationFormRedirectControllerTest.cls
@IsTest
public with sharing class ApplicationFormRedirectControllerTest {

    @TestSetup
    public static void setup() {
        TestDataGenerator.createDocuSignSettings();
    }

    @IsTest
    public static void test() {

        String powerformId = DocuSign_Settings__c.getOrgDefaults().DocuSign_Powerform_Id__c;
        PageReference pageRef = Page.ApplicationFormRedirect;
        pageRef.getParameters().put('pf', powerformId);
        Test.setCurrentPage(pageRef);

        ApplicationFormRedirectController controller = new ApplicationFormRedirectController();

        controller.redirect();
    }

}