unpackaged/main/default/objects/Box_OAuth__c/Box_OAuth__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Stores each user's authentication token for Box</description>
    <label>Box OAuth</label>
</CustomObject>

unpackaged/main/default/objects/Box_OAuth__c/fields/Auth_Token__c.field-meta.xml
<CustomField>
    <fullName>Auth_Token__c</fullName>
    <description>The User's Auth Token</description>
    <label>Auth Token</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Box_OAuth__c/fields/AuthTokenExpires__c.field-meta.xml
<CustomField>
    <fullName>AuthTokenExpires__c</fullName>
    <description>Date/Time the auth token expires. If expired and the refresh token is still valid, then a refresh will be needed to get a new auth token.</description>
    <label>Auth Token Expires</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Box_OAuth__c/fields/RefreshTokenExpires__c.field-meta.xml
<CustomField>
    <fullName>RefreshTokenExpires__c</fullName>
    <description>Date / Time the Refresh Token expires. If expired, then the user will need to reauthenticate with Box.</description>
    <label>Refresh Token Expires</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Box_OAuth_Object__c/Box_OAuth_Object__c.object-meta.xml
<CustomObject>
    <label>Box OAuth Object</label>
    <nameField>
        <label>Box OAuth Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box OAuth Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Box_OAuth_Object__c/fields/Auth_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Auth_Endpoint__c</fullName>
    <label>Auth Endpoint</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Box_OAuth_Object__c/fields/Auth_Token__c.field-meta.xml
<CustomField>
    <fullName>Auth_Token__c</fullName>
    <label>Auth Token</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Box_OAuth_Object__c/fields/Auth_Token_Expires__c.field-meta.xml
<CustomField>
    <fullName>Auth_Token_Expires__c</fullName>
    <label>Auth Token Expires</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Box_OAuth_Object__c/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <label>Client Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Box_OAuth_Object__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <label>Client Secret</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Box_OAuth_Object__c/fields/Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token__c</fullName>
    <label>Refresh Token</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Box_OAuth_Object__c/fields/Refresh_Token_Expires__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token_Expires__c</fullName>
    <label>Refresh Token Expires</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/OAuthSettings__c/OAuthSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to store OAuth settings</description>
    <label>OAuth Settings</label>
</CustomObject>

unpackaged/main/default/objects/OAuthSettings__c/fields/AuthEndpoint__c.field-meta.xml
<CustomField>
    <fullName>AuthEndpoint__c</fullName>
    <description>The OAuth endpoint.</description>
    <label>Auth Endpoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/OAuthSettings__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <label>Client ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OAuthSettings__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <label>Client Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/BoxAuthTest.cls
@isTest
private class BoxAuthTest {
    static Box_OAuth_Object__c boxAuthObj;
    static {
    	
    	boxAuthObj = new Box_OAuth_Object__c();
    	boxAuthObj.Name = '123';
        boxAuthObj.Auth_Endpoint__c = 'https://www.box.com/api/2.0/';
        boxAuthObj.Auth_Token__c = '1234567890';
        boxAuthObj.Refresh_Token__c = '1234567890';
        boxAuthObj.Auth_Token_Expires__c = Datetime.now().addSeconds(3600);
        boxAuthObj.Refresh_Token_Expires__c = Datetime.now().addDays(60);
        boxAuthObj.Client_Id__c = '12345';
        boxAuthObj.Client_Secret__c  = '12345';
        insert boxAuthObj;
        
        oAuthSettings__c oAuthSetting = new oAuthSettings__c(
            Name = 'Box',
            AuthEndPoint__c = 'https://www.box.com/api/2.0/',
            ClientId__c = '123456',
            ClientSecret__c = '123456');
        insert oAuthSetting;
        
    }
    
    @isTest static void testOAuthFlow() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new BoxMockHttpResponse());
        
        Test.setCurrentPage(Page.boxauth);
        BoxAuth ba = new BoxAuth();
        PageReference authPage = ba.requestToken();
        URL authURL = new URL(authPage.getUrl());
        System.assertEquals('/api/2.0/authorize', authURL.getPath());
        System.assertEquals('code', authPage.getParameters().get('response_type'));

        Test.setCurrentPage(Page.boxauth);
        System.assertEquals(null, ba.checkCode(), 'Null should have been returned because no code was passed to the page');
        System.currentPagereference().getParameters().put('code', '123456');
        
        ba.checkCode();
        System.assertEquals('T9cE5asGnuyYCCqIZFoWjFHvNbvVqHjl', BoxAuth.authInfo.Auth_Token__c);

        System.assert(ba.isAuthorized, 'The user should be authorized to Box.');

        Test.stopTest();
    }

    @isTest static void testCurrentUser() {
        Test.setMock(HttpCalloutMock.class, new BoxMockHttpResponse());
        Box_OAuth__c boxOAuth = new Box_OAuth__c(); //SetupOwnerId = UserInfo.getUserId()
        boxOAuth.Auth_Token__c = '1234567890';
        boxOAuth.Refresh_Token__c = '1234567890';
        boxOAuth.AuthTokenExpires__c = Datetime.now().addSeconds(3600);
        boxOAuth.RefreshTokenExpires__c = Datetime.now().addDays(60);
        insert boxOAuth;

        boxAuthObj.Auth_Endpoint__c = '';
        boxAuthObj.Auth_Token__c = '1234567890';
        boxAuthObj.Refresh_Token__c = '1234567890';
        boxAuthObj.Auth_Token_Expires__c = Datetime.now().addSeconds(3600);
        boxAuthObj.Refresh_Token_Expires__c = Datetime.now().addDays(60);
        boxAuthObj.Client_Id__c = '12345';
        boxAuthObj.Client_Secret__c  = '12345';
        update boxAuthObj;
		
        Test.startTest();
        BoxAuth ba = new BoxAuth();
        BoxObject2.User boxUser = ba.currentUser;
        System.assertEquals('sean+awesome@box.com', boxUser.login);
        Test.stopTest();
    }

    @isTest static void testRefreshToken() {
        Test.setMock(HttpCalloutMock.class, new BoxMockHttpResponse());
        Box_OAuth__c boxOAuth = new Box_OAuth__c(); //SetupOwnerId = UserInfo.getUserId()
        boxOAuth.Auth_Token__c = '1234567890';
        boxOAuth.Refresh_Token__c = '1234567890';
        boxOAuth.AuthTokenExpires__c = Datetime.now().addSeconds(-3600);
        boxOAuth.RefreshTokenExpires__c = Datetime.now().addDays(60);
        insert boxOAuth;
		
        boxAuthObj.Auth_Endpoint__c = '';
        boxAuthObj.Auth_Token__c = '1234567890';
        boxAuthObj.Refresh_Token__c = '1234567890';
        boxAuthObj.Auth_Token_Expires__c = Datetime.now().addSeconds(-3600);
        boxAuthObj.Refresh_Token_Expires__c = Datetime.now().addDays(60);
        boxAuthObj.Client_Id__c = '12345';
        boxAuthObj.Client_Secret__c  = '12345';
        update boxAuthObj;
		
        Test.startTest();
        BoxAuth.refreshToken();
        System.assertEquals('T9cE5asGnuyYCCqIZFoWjFHvNbvVqHjl', BoxAuth.authInfo.Auth_Token__c);
        Test.stopTest();
    }
/*
    @isTest static void testExpireRefreshToken() {
        Box_OAuth__c boxOAuth = new Box_OAuth__c(); //SetupOwnerId = UserInfo.getUserId()
        boxOAuth.Auth_Token__c = '1234567890';
        boxOAuth.Refresh_Token__c = '1234567890';
        boxOAuth.AuthTokenExpires__c = Datetime.now().addSeconds(-3600);
        boxOAuth.RefreshTokenExpires__c = Datetime.now().addDays(-60);
        insert boxOAuth;

        boxAuthObj.Auth_Token__c = '1234567890';
        boxAuthObj.Refresh_Token__c = '1234567890';
        boxAuthObj.Auth_Token_Expires__c = Datetime.now().addSeconds(-3600);
        boxAuthObj.Refresh_Token_Expires__c = Datetime.now().addDays(-60);
        boxAuthObj.Client_Id__c = '12345';
        boxAuthObj.Client_Secret__c  = '12345';
        update boxAuthObj;

        Test.startTest();
        try {
            Box_OAuth__c oauth = BoxAuth.authInfo;
        } catch (BoxAuthException e) {
            return;
        }
        Test.stopTest();
        System.assert(false, 'An exception wasn\'t thrown because the refresh token was not valid');
    }
*/
    @isTest static void testNoAuthInfo() {
    	boxAuthObj.Auth_Endpoint__c = null;
        boxAuthObj.Auth_Token__c = null;
        boxAuthObj.Refresh_Token__c = null;
        boxAuthObj.Auth_Token_Expires__c = null;
        boxAuthObj.Refresh_Token_Expires__c = null;
        boxAuthObj.Client_Id__c = null;
        boxAuthObj.Client_Secret__c  = null;
        update boxAuthObj;
        
        BoxAuth ba = new BoxAuth();
        Test.startTest();
        System.assert(!ba.isAuthorized, 'The user should not be authorized since no token has been set.');
        try {
            Box_OAuth__c oauth = BoxAuth.authInfo;
        } catch (BoxAuthException e) {
            return;
        }
        Test.stopTest();
        //System.assert(false, 'An exception wasn\'t thrown even though no auth token was set');
    }
/*
    @isTest static void testRevokeToken() {
        Test.setMock(HttpCalloutMock.class, new BoxMockHttpResponse());
        Box_OAuth__c boxOAuth = new Box_OAuth__c(); //SetupOwnerId = UserInfo.getUserId()
        boxOAuth.Auth_Token__c = '1234567890';
        boxOAuth.Refresh_Token__c = '1234567890';
        boxOAuth.AuthTokenExpires__c = Datetime.now().addSeconds(3600);
        boxOAuth.RefreshTokenExpires__c = Datetime.now().addDays(60);
        insert boxOAuth;
		
        boxAuthObj.Auth_Token__c = '1234567890';
        boxAuthObj.Refresh_Token__c = '1234567890';
        boxAuthObj.Auth_Token_Expires__c = Datetime.now().addSeconds(3600);
        boxAuthObj.Refresh_Token_Expires__c = Datetime.now().addDays(60);
        boxAuthObj.Client_Id__c = '12345';
        boxAuthObj.Client_Secret__c  = '12345';
        update boxAuthObj;
		
        Test.startTest();
            BoxAuth ba = new BoxAuth();
            ba.revokeToken();
        Test.stopTest();

        System.assert(!ba.isAuthorized, 'There should be no token stored since it has been revoked.');
    }
    */
}