unpackaged/main/default/objects/Opportunity/fields/Ocrolus_Book_Name__c.field-meta.xml
<CustomField>
    <fullName>Ocrolus_Book_Name__c</fullName>
    <label>Ocrolus Book Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Ocrolus_Book_PK__c.field-meta.xml
<CustomField>
    <fullName>Ocrolus_Book_PK__c</fullName>
    <label>Ocrolus Book PK</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Ocrolus_Book_UUID__c.field-meta.xml
<CustomField>
    <fullName>Ocrolus_Book_UUID__c</fullName>
    <label>Ocrolus Book UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/OcrolusNewBookBL.cls
public with sharing class OcrolusNewBookBL {

    public OcrolusNewBookRequest generateForOpp(Opportunity opp) {
        OcrolusNewBookRequest request = new OcrolusNewBookRequest();
        request.name = opp.Name + ' (' + opp.Id + ') - ' + Datetime.now();
        return request;
    }

    public void updateBookFields(Opportunity opp, OcrolusNewBookResponse response) {
        opp.Ocrolus_Book_Name__c = response.response.name;
        opp.Ocrolus_Book_PK__c = response.response.pk;
        opp.Ocrolus_Book_UUID__c = response.response.uuid;
    }

}