unpackaged/main/default/objects/Opportunity/fields/Submissions__c.field-meta.xml
<CustomField>
    <fullName>Submissions__c</fullName>
    <description>Counts all submissions records that are in the Underwriting status, allowing a validation rule to only allow the stage update to Funded (on Opp) when no submission records are in Underwriting status</description>
    <label>Submissions</label>
    <summaryFilterItems>
        <field>Submissions__c.Bank_Status__c</field>
        <operation>equals</operation>
        <value>Underwriting</value>
    </summaryFilterItems>
    <summaryForeignKey>Submissions__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Submissions__c/Submissions__c.object-meta.xml
<CustomObject>
    <label>Submissions</label>
    <nameField>
        <displayFormat>Submission {000000}</displayFormat>
        <label>Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Submissions__c/fields/Bank_Status__c.field-meta.xml
<CustomField>
    <fullName>Bank_Status__c</fullName>
    <label>Bank Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Underwriting</fullName>
                <default>true</default>
                <label>Underwriting</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Submissions__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Submissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Submissions__c/fields/Time_Until_Approved__c.field-meta.xml
<CustomField>
    <fullName>Time_Until_Approved__c</fullName>
    <label>Time Until Approved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Submissions__c/fields/TimeApproved__c.field-meta.xml
<CustomField>
    <fullName>TimeApproved__c</fullName>
    <label>Time Approved</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/SubmissionTriggerHandler.cls
public with sharing class SubmissionTriggerHandler {
	
	
	public SubmissionTriggerHandler() {

	}
	
	public void onBeforeInsert() { 
		 
		if(!Trigger.isExecuting) {
			return;
		} 
		
		List<Submissions__c> newSubmissionList = (List<Submissions__c>) Trigger.new;
		for(Submissions__c submission : newSubmissionList) {
			if(submission.Bank_Status__c == 'Approved'
				&& submission.TimeApproved__c == null) {
					submission.TimeApproved__c = DateTime.now();
					submission.Time_Until_Approved__c = 0;
			}
		}
		
	}
	
	public void onBeforeUpdate() {
		
		if(!Trigger.isExecuting) {
			return;
		}
		
		List<Submissions__c> newSubmissionList = (List<Submissions__c>) Trigger.new;
		Map<Id, Submissions__c> oldSubmissionMap = (Map<Id, Submissions__c>) Trigger.oldMap;
		for(Submissions__c submission : newSubmissionList) {
			if(submission.Bank_Status__c == 'Approved'
				&& oldSubmissionMap.get(submission.Id).Bank_Status__c <> 'Approved'
				&& submission.TimeApproved__c == null) {
					DateTime now = DateTime.now();
					submission.TimeApproved__c = now;
					submission.Time_Until_Approved__c = this.getTimeUntilApproved(submission.CreatedDate, now);
			}
		}
		
	}
	public void onAfterInsert() {
        updateOpportunityStage(Trigger.new);
    }
	public void onAfterUpdate() {
		updateOpportunityStage(Trigger.new);
	}
    public void onAfterDelete() {
        updateOpportunityStage(Trigger.old);
    }
    
    private void updateOpportunityStage(List<Submissions__c> submissionList) {
        
		System.debug(submissionList[0].Opportunity__c);
		System.debug(submissionList[0].Bank_Status__c);
		List<String> oppIdList = new List<String>();
		for(Submissions__c submission : submissionList)
			oppIdList.add(submission.Opportunity__c);
		List<Opportunity> oppList = [SELECT Id, StageName, (SELECT Id, Bank_Status__c FROM Submissions__r) FROM Opportunity WHERE Id IN :oppIdList];
		boolean changeStageToUnderwritingDeclined = false;
		boolean changeStageToUnderwriting = false;
        for(Opportunity opp : oppList) {
            changeStageToUnderwritingDeclined = true;
			for(Submissions__c submission : opp.Submissions__r)
			{
				if(opp.StageName != 'Underwriting' || submission.Bank_Status__c != 'Declined')
					changeStageToUnderwritingDeclined = false;					
				if(opp.StageName == 'Underwriting - Declined' && submission.Bank_Status__c == 'Underwriting')
					changeStageToUnderwriting = true;
			}
            System.debug(changeStageToUnderwritingDeclined);
            if(changeStageToUnderwritingDeclined)
				opp.StageName = 'Underwriting - Declined';
			else if(changeStageToUnderwriting)
				opp.StageName = 'Underwriting';
		}
		System.debug(oppList[0].StageName);
		System.debug(oppList[0]);
		System.debug(oppList);
		update oppList;
    }
	
	private decimal getTimeUntilApproved(DateTime startTime, DateTime endTime) {
		BusinessHours bh = [SELECT Id FROM BusinessHours WHERE IsDefault = true];
		Long diff = BusinessHours.diff(bh.Id, startTime, endTime);
		Decimal num = diff /1000.0 / 60.0 / 60.0;
		Decimal fixedNum = num.setScale(2, RoundingMode.HALF_DOWN);
		return fixedNum;
	}
    
}